### ISSUE TITLE
Unity Version:2018.1.0b8  error  Assembly has reference to non-existent assembly

### ISSUE THREAD

**Issue by Maomao110** [Unity-Technologies/ScriptableRenderPipeline#1003]
A new Unity beta version
A new Project
And Copy the project from the github , paste to the new project

Then the errors come out:
       Assembly has reference to non-existent assembly 'com.unity.postprocessing.Runtime' (Assets/ScriptableRenderPipeline/ScriptableRenderPipeline-master/ScriptableRenderPipeline/LightweightPipeline/LWRP/Editor/com.unity.render-pipelines.lightweight.Editor.asmdef)

**Comment by stramit** [comment]
See case 984
