### ISSUE TITLE
Long path name causes source control issues

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/ScriptableRenderPipeline#1007]
"/Assets/ScriptableRenderPipeline/Tests/GraphicsTests/RenderPipeline/HDRenderPipeline/Scenes/1xxx_Materials/1101_Unlit/Emissive_Color/18_Unlit_Textured_Trans_Alpha_PreRefractionPass_AlphaCutoff_Doubleside.mat.meta"

is 212 characters worth of path.  This long path causes issues when using source control unless I create a project in an intentionally high-level folder.

Can long path names like this be pruned down?

**Comment by sebastienlagarde** [comment]
This issue also affect us. This is really sad for windows OS... @RemyUnity. Please take this in consideration. Thanks

**Comment by sebastienlagarde** [comment]
This will be updated soon.
