### ISSUE TITLE
Directional Light Culling Masks don't work properly

### ISSUE THREAD

**Issue by mrlinds** [Unity-Technologies/ScriptableRenderPipeline#1019]
If you make a scene with objects set to two different layers and then make two directional lights set to affect those layers separately, the directional lights will still affect both layers.

**Comment by mrlinds** [comment]
Ah, forgot to note that I'm seeing this in Lightweight Pipeline

**Comment by sebastienlagarde** [comment]
@phi-lira is it still the case?

**Comment by phi-lira** [comment]
LWRP treats directional lights as globals to avoid branching and indexing and provide a fast shading path for them. I've added to my backlog to look for an alternative performant way for this.
