### ISSUE TITLE
ARBackgroundRenderer support

### ISSUE THREAD

**Issue by iBicha** [Unity-Technologies/ScriptableRenderPipeline#1033]
[ARBackgroundRenderer](https://docs.unity3d.com/ScriptReference/XR.ARBackgroundRenderer.html) relies on command buffers to fill the screen with a material before opaque rendering.

This class is relied on to render background in AR apps (ARCore, ARInterface, etc)
I think it should be supported by - at least - the LWRP, so it would work out of the box on existing projects (I'm seeing this in issues on Github in their respective repos already, people want SRP support)

So I think the approach is, either have a way to let the `ARBackgroundRenderer` add it's command buffer to the current render pipeline, or have the LWRP support it out of the box.

Another approach is, since the `ARBackgroundRenderer` adds a command buffer to the camera, shouldn't the render pipelines, by default, loop through these commands and add them to the list before the submit?

**Comment by iBicha** [comment]
https://github.com/google-ar/arcore-unity-sdk/issues/131#issuecomment-370695963

**Comment by iBicha** [comment]
While we're at it, shouldn't command buffers added using [Camera.AddCommandBuffer](https://docs.unity3d.com/ScriptReference/Camera.AddCommandBuffer.html) be retrieved and executed in the render pipeline in the appropriate order? It should be at least an option in the pipeline asset, whether to execute command buffers on individual cameras or not.

**Comment by robbiesri** [comment]
Hey @iBicha , sorry for lag here. Tim and Seb can talk more about this but there is support coming for callbacks in the pipelines (before rendering and before each camera). I’d guess the AR background setup could be scheduled somewhere in there. However, it’s not specifically before opaques...

Re: Camera.AddCommandBuffer
Part of jumping over to these new pipelines is breaking away from legacy infrastructure. The CameraEvents don’t even make sense with the new Pipelines. That’s not to say that the team isn’t thinking about the issue, but I wouldn’t anticipate legacy CameraEvent hookpoints.

**Comment by robbiesri** [comment]
Check out #898 for more deets

**Comment by iBicha** [comment]
Thanks for the reply, as far as I know, `ARBackgroundRenderer` adds its commands on `BeforeGBuffer` and `BeforeForwardOpaque`, which makes the most sense if the purpose is to replace the clearing/skybox rendering.

I know this new system trying to revamp rendering from the ground up, I'm just saying, to get a smoother transition, maybe we can have a `Legacy rendering support` checkbox in the Asset settings. At least for a couple of releases of Unity, before deprecating it once and for all. I know a few fellow game developers who did not upgrade Unity for YEARS because "it broke their project" or "the models are all pink", and depending on the size of the project, or the technical skills of the developers, some people can't afford to upgrade, and this would hurt the adoption of the newer versions of Unity. So making the transition smoother by supporting legacy rendering at first, until it's time to kill it. Just my $.02

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/srp-arbackgroundrenderer-support
