### ISSUE TITLE
LWRP + XR: Investigate stereoEyeIndex VS->PS parameter issue in LWScreenSpaceShadows.shader

### ISSUE THREAD

**Issue by robbiesri** [Unity-Technologies/ScriptableRenderPipeline#1049]
When updating LightweightScreenSpaceShadows.shader for XR, I ran into an issue where I was getting an incorrect unity_StereoEyeIndex in the fragment shader.

This was very surprising because the Interpolators struct had the  UNITY_VERTEX_OUTPUT_STEREO parameter declared (uint stereoEyeIndex : SV_RenderTargetArrayIndex), which specifies the slice that will be rasterized to.  The rasterization was working, but the usage of stereoEyeIndex in the fragment shader was not.  I was able to use the InstanceID to extract the correct unity_StereoEyeIndex, but the Interpolators value _should_ be correct!

Anyway, we need to investigate why this isn't working as expected.

This is the code in question:
https://github.com/Unity-Technologies/ScriptableRenderPipeline/blob/18c31f9612ddc3b62dcc9de57d815de4de2dbb72/ScriptableRenderPipeline/LightweightPipeline/LWRP/Shaders/LightweightScreenSpaceShadows.shader#L56

**Comment by phi-lira** [comment]
@brandon-unity3d does your PR fixes this?

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-lwrp-plus-xr-investigate-stereoeyeindex-vs-ps-parameter-issue-in-lwscreenspaceshadows-dot-shader
