### ISSUE TITLE
No MSAA in VR when using Lightweight Asset

### ISSUE THREAD

**Issue by julhe** [Unity-Technologies/ScriptableRenderPipeline#1062]
MSAA is working fine in the editor and game view, but I once press play and enter VR, its gone.

**Comment by robbiesri** [comment]
What version is this?  I fixed up some issues last week.  Not sure when they got pushed out through Package Manager (if they have, tbh).

**Comment by julhe** [comment]
2018.1.0b8

**Comment by robbiesri** [comment]
Did you get SRP from here (GitHub) or Package Manager?

**Comment by julhe** [comment]
Got it from GitHub. Im using OpenVR if this is of any interest.

**Comment by robbiesri** [comment]
Hrmmmm, it should be working. I just tested locally, was working.  I did just fix a bunch of other XR issues with this PR:
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/1020

Which landed after your version.  So...maybe give this as a try, if it works with your version of Unity?

**Comment by julhe** [comment]
Alright, it's working in the most recent version. Thank you! 😄
