### ISSUE TITLE
Assembly has reference to non-existent assembly 'com.unity.postprocessing.Runtime' 

### ISSUE THREAD

**Issue by aammfe** [Unity-Technologies/ScriptableRenderPipeline#1122]
Hello !
I have unity 2018.1.0b11 and clone this repo in project  and getting this error. 

![image](https://user-images.githubusercontent.com/11896817/37869141-2b98ecc0-2fd4-11e8-9f73-38e7a09b6ef5.png)

Assembly has reference to non-existent assembly 'com.unity.postprocessing.Runtime' (Assets/SRP/ScriptableRenderPipeline/ScriptableRenderPipeline/LightweightPipeline/LWRP/com.unity.render-pipelines.lightweight.Runtime.asmdef)

![image](https://user-images.githubusercontent.com/11896817/37869144-30dff21e-2fd4-11e8-981a-20cd58a4f09b.png)

**Comment by giordi91** [comment]
did you do the submodule init? seems like post processing has not been cloned, which does not happen by default by being a git submodule
