### ISSUE TITLE
[Question] Geometries not showing up

### ISSUE THREAD

**Issue by giordi91** [Unity-Technologies/ScriptableRenderPipeline#1149]
Good afternoon, I am trying to use the SRP and having an hard time to get it to roll, I was able to follow the blog post correctly for clearing the screen:
https://blogs.unity3d.com/2018/01/31/srp-overview/

It doesn't seem to work for opaque and opaque + transparent, I do get the sky-box but the geometry doesn't show up, just tried dropping a box and a cube, although if selected wire-frame shows up. I tired to play with several settings, forward/deferred, hdr or not hdr and so on Still nothing. I also tried this other example : 
https://github.com/keijiro/Retro3DPipeline

Still having the same issue.
OS: Windows
Unity Version : 2018.1.b10-13. 

Am I missing something to get it to work?

Thanks for the help
M.

**Comment by gnlnx** [comment]
did you set an SRP asset in Edit/Project Settings/Graphics?

**Comment by giordi91** [comment]
Yes, I am able to run the solid color pipeline or the unity provided one (from blog post) and the Retro3D,
respectively getting:
1) solid color background (the one I picked), can change etc
2) Just skybox and geo wireframe if geo selected
3) grey background as expected.

So overall the pipeline is getting triggered fine, just the geo really doesnt want to get through. Other than the asset is there anything else I need to do? Any tip of the matter would be helpful. 
PS: Sorry for later reply I was off-site at work for few days.

**Comment by sebastienlagarde** [comment]
We have observe this issue internally on one configuration, but it appear that this is also present with buitin Unity. As a confirmation can you check that a regular new level of built-in unity is correctly display ?

**Comment by giordi91** [comment]
Hi, can you please clarify what you mean by: "regular new level of built-in unity", 
Should I try with a fresh project in 2018.b13 and latest master for SRP?

**Comment by sebastienlagarde** [comment]
Hey, I mean remove any render pipeline from Graphic Settings, and then do File new scene. Add some sphere and plane, check that they are display. In our case it is display only in GameView but no in SceneView and for built-in as well as any SRP.

**Comment by giordi91** [comment]
What is the latest beta that works with master of this repository? I am trying to make a new project from scratch in b13, but it straight up fail to compile several of the shaders for some reason, I think last time I used b8 and opened with b13 and worked. 

Would be good to have fully working snapshot that can be downloaded and just dropped in assets, we have restricted internet access so any automatic download or clone wont work, which makes this new package direction particularly painful for us.

**Comment by sebastienlagarde** [comment]
>What is the latest beta that works with master of this repository?
Master is aiming to work with internal version, only tagged version work with public release.

>Would be good to have fully working snapshot that can be downloaded and just dropped in assets
This is the purpose of tagged version.

>but it straight up fail to compile several of the shaders for some reason
This is certainly an issue due to unable to open shader include file, we get this problem a lot and currently try to solve it.

**Comment by giordi91** [comment]
I have done both work around and no luck. Still same errors, can you confirm me that the code in master of SRP is supposed to work with beta 13? (by work i mean at least compile with no errors, so that I can try the rest).

**Comment by giordi91** [comment]
After keep deleting the Library and ShaderCache folders several times it loaded correctly, but the issue with geometry not showing up still appear both in editor and game views. This is in a new project in b13.

**Comment by giordi91** [comment]
Any news on this?

**Comment by sebastienlagarde** [comment]
> Still same errors, can you confirm me that the code in master of SRP is supposed to work with beta 13? No master is aiming at working with internal version, for beta 13 you need to use this tag: https://github.com/Unity-Technologies/ScriptableRenderPipeline/releases/tag/unity-2018.1.0b13

>but the issue with geometry not showing up still appear both in editor and game views
Can you confirm that you haven't the issue with buitin Unity? In the case we have observed this it was not a SRP problem but a general unity problem. And fix should come with new binaries of 2018.1 (that have sadly been delayed a bit).

**Comment by giordi91** [comment]
Can you clarify what you mean by builtin unity?

**Comment by giordi91** [comment]
Oh I see, no regular pipeline is all good, I am using a mix of 2018.b13 and latest 2017 for my daily work. Old pipeline works fine, even with custom deferred shaders etc, so only  an Issue I am seeing with 2018.b*

**Comment by sebastienlagarde** [comment]
ok, so it is rather unexpected. Is it possible that you zip your scene/project that don't work (or have a small new scene) ? So we can test it. Thanks

**Comment by giordi91** [comment]
I will need to double check here at work, due to the policy not sure if that can be done through github, we might have to do it through internal channel. I will get back to you. I will also test with the correct handle b13.

**Comment by sebastienlagarde** [comment]
I you create a new project with your current version, do you have the problem?
i.e launch your unity version, create a new project, copy/paste the folder ScriptableRenderPipeline (or the package you use), create a cube, assign the render pipeline, is the cube visible ?

If it isn't, we just need your project (with should contain this scene with a cube and SRP source code) and the exact binaries version used (can be fonud in about windows). 

Thanks

**Comment by giordi91** [comment]
I just did that on my surfacePRO that has internet collection, downloaded b13 fresh, installed SRPHD, SRPCore, ShaderGraph and PostProcessing from package manager. Create a cube all good (not using any SRP). Then I clone the example from SRP-Blog post repository (from Unity's blog post), create opaque render pipe, cube disappear, if I select it, I only see the wireframe. 

I am gonna figure out how to get you the archive. I ll get back to you.

**Comment by giordi91** [comment]
Please find attached the zip, the binary used is 2018.1.0b.13

[srpagain.zip](https://github.com/Unity-Technologies/ScriptableRenderPipeline/files/1951296/srpagain.zip)


Here the setup:
![screenshot 26](https://user-images.githubusercontent.com/2525797/39308089-7a7f8f46-495c-11e8-8e5f-2c30a9525dea.png)
![screenshot 27](https://user-images.githubusercontent.com/2525797/39308092-7d07451a-495c-11e8-850d-3a25660d4856.png)
![screenshot 28](https://user-images.githubusercontent.com/2525797/39308155-9f821c8c-495c-11e8-9579-3982d66645ff.png)

**Comment by sebastienlagarde** [comment]
Thanks!

@RemyUnity can you check this ^^.

**Comment by RemyUnity** [comment]
Hello @giordi91 

I took a look at your project, and apparently you simply forgot one specificity of SRP :

You are using the OpaqueAssetPipe in your project, and if you look at OpaqueAssetPipe.cs line 50 : 
`var settings = new DrawRendererSettings(camera, new ShaderPassName("BasicPass"));`
You'll notice that this pipe is coded so that it will only render object with shaders that have a passed named "BasicPass".

In your scene the cube is using Unity's default material, that doesn't implement a pass with this name.
But if you assign the material located at **Assets\SRP-Demo\2-OpaqueAssetPipe\SRP_BasicPassColor.mat** the cube will now be displayed.
Also, the demo scene **Assets\SRP-Demo\DemoScene.unity** will be displayed correctly if you use the different renderpipes from the demo project.

**Comment by giordi91** [comment]
Thank you for checking into this, might be worth to specify that in the blog post since I was trying to write my own from scratch. 
PS: since we are here, that is what I get if I create a new project with the HD render pipeline preset.
![screenshot 29](https://user-images.githubusercontent.com/2525797/39348845-aa7b6f96-49f0-11e8-8262-a282f781d1af.png)
![screenshot 30](https://user-images.githubusercontent.com/2525797/39348846-aa8f0cea-49f0-11e8-8969-4a6661af2959.png)
I tested with the provided material and works fine,  I am closing this.

**Comment by RemyUnity** [comment]
This can happen from time to time : dependencies are not loaded in the right order in the packages. Usually simply re-opening the editor should fix the issue. Or entering play mode will re-create the render pipeline and can fix it too.
