### ISSUE TITLE
Lightweight rendering with tilemap Bug

### ISSUE THREAD

**Issue by KoalaHao** [Unity-Technologies/ScriptableRenderPipeline#1192]
Bug detail:
Tiles disappear in game view, when tile is not visible in the scene view

Steps to reproduce:
1. create a new project
2. install Lightweight rendering pipeline
3. add a tilemap to the scene with a few tiles
4. make sure the tiles are in view by the main camera
5. move the everything out of view in the scene view, (or simply close the scene view)
6. click on play, **tiles are no longer visible in game view**
7. reposition the scene view so that you can see the tiles in the scene,  tiles appear in the game view

this also happens when you build and run

**Comment by sebastienlagarde** [comment]
@phi-lira any thought ?

**Comment by phi-lira** [comment]
Hey @KoalaHao. I'm doing a bugfix sweep next week. This bug is on the list. I'll get back with more info on it then.

**Comment by phi-lira** [comment]
There's a fix inbound for this issue. It requires engine changes so it might take a little bit while the fix is available.

**Comment by iceandstorm** [comment]
same problem...  any news?

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-lightweight-rendering-with-tilemap-bug
