### ISSUE TITLE
RenderPipelines not showing up in project

### ISSUE THREAD

**Issue by clankill3r** [Unity-Technologies/ScriptableRenderPipeline#1203]
I try to install the the lightweight render pipeline, i'm on mac.
I have unity 2018.1.0b13 installed using unity hub.
I installed the lighweight render pipeline using the new package manager.
There it says `1.1.2 preview` so maybe they are not compatible?

In my project window nothing shows up:

<img width="341" alt="screen shot 2018-04-15 at 14 50 49" src="https://user-images.githubusercontent.com/738650/38778607-7095653a-40bc-11e8-849c-a6d7b791b1fc.png">

Therefor I can never select something here:

<img width="314" alt="screen shot 2018-04-15 at 14 52 22" src="https://user-images.githubusercontent.com/738650/38778625-a7033b2e-40bc-11e8-80f6-b322feb03e75.png">

**Comment by ylluminarious** [comment]
@sebastienlagarde I am having the same issue, but I don't see the `Rendering` dropdown item. I'm on macOS 10.13.4 and Unity 2018.1.0f2.

**Comment by sebastienlagarde** [comment]
If you don't see the "Rendering" menu like on the screenshot above, it mean the render pipeline don't compile, check the console and see if there is any error

**Comment by ylluminarious** [comment]
@sebastienlagarde Could it be due to an error in a 3rd-party plugin?

**Comment by ylluminarious** [comment]
@sebastienlagarde Hmm, it seems I've resolved some errors that *were* there, but are gone now and yet I still can't see the `Rendering` menu item. What can I do now? Is there some other way to create the Pipeline Asset?

**Comment by ylluminarious** [comment]
@sebastienlagarde I managed to solve my issue [here.](https://github.com/Unity-Technologies/ScriptableRenderPipeline/issues/1359#issuecomment-389347041)
