### ISSUE TITLE
[Question] Scene Mask

### ISSUE THREAD

**Issue by traggett** [Unity-Technologies/ScriptableRenderPipeline#1204]
Hey! I've been experimenting with the new ScriptableRenderPipeline and I'm trying to work out how to render objects from a particular scene

Could you explain how the sceneMask property works in ScriptableCullingParameters? I've experimented with setting different values on it and it seems to render objects from all scenes if the value is less than zero, or no objects if it's greater than zero.

Is it possible to use it to filter or cull objects based on their scene? Or alternatively could I modify or use a custom FilterRenderersSettings to filter by scene?

Thanks a lot for the help!
Tom

**Comment by traggett** [comment]
Poke :)
Can anyone explain how the sceneMask or cullingMask in ScriptableCullingParameters are supposed to be used? The docs unfortunately say nothing and can't find anything in the source code.
Thanks!

**Comment by FlorinUnity** [comment]
Hi,
we moved the Question to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/srp-question-scene-mask
