### ISSUE TITLE
Dynamic Batching

### ISSUE THREAD

**Issue by 0jb** [Unity-Technologies/ScriptableRenderPipeline#1207]
I couldn't find any info about this, I'm testing lightweight rendering pipeline and seems that dynamic batching is not there.

What I did:
Opened 007_LitShaderMaps.scene, created a quad with Standard shader and duplicated. Then I verified that the number of batches increased.

Forward_Asset doesn't seem to work with dynamic batching as well.

If I deactivate SRP (go to graphic settings and delete the SRP reference) dynamic batching works fine.

Am I doing something wrong or is this not implemented yet? Is this part of SRP, will the API do it on a method by itself or do we need to code batching on the render loop?
Thanks!

**Comment by sebastienlagarde** [comment]
@stramit Any though?

**Comment by sebastienlagarde** [comment]
Haven't more info about if it is supported or not, but we know that for SRP we want to discourage usage of DynamicBatching as it is inefficient in most case. For speed purpose ,we have a new SRP batcher coming in 2018.2.

**Comment by phi-lira** [comment]
Hey, SRP does support dynamic batching, however the default behavior is to disable it by default. 
I'm adding a setting on the LWRP asset so one can choose to enabled Dynamic Batching and Instancing in the renderer.

**Comment by phi-lira** [comment]
Fixed in #1367 Support for Dynamic Batching can be requested in the pipeline asset.
We will generate a new package with this fix tomorrow.
