### ISSUE TITLE
MSVO lacking overlay mode for stylised rendering?

### ISSUE THREAD

**Issue by hippocoder** [Unity-Technologies/ScriptableRenderPipeline#1233]
Hello!

I wondered if I was using it wrong, but for a large portion of projects which use stylised rendering, MSVO settings would benefit from an overlay mode - ie entirely ignoring the lighting in the scene, for clay, cartoon, NPR rendering.

Please consider! :)

**Comment by sebastienlagarde** [comment]
Are you talking inside a particular pipeline (i.e HD?) or your own SRP?

MSVO in itself just calculate the ambient occlusion, its application is render pipeline specific.

In the case of HDRP it happen in PostEvaluateBSDF() of lit.hlsl file. Here you can tweak the code to remove all lighting where there is AO (either direct or indirect).

**Comment by hippocoder** [comment]
Thanks, this is what I was looking for.
