### ISSUE TITLE
Apply Range Attenuation currently non functioning

### ISSUE THREAD

**Issue by hippocoder** [Unity-Technologies/ScriptableRenderPipeline#1264]
https://i.imgur.com/dWEfYmL.png

I have tested on 3 different machines, 2018.1 and 2018.2 with 1.1.4 and 1.1.5 and just wanted to confirm that it is currently expected not to work yet (or possibility of bug).

Thanks!

**Comment by sebastienlagarde** [comment]
I re-open it, as it is a valid issue :)

**Comment by sebastienlagarde** [comment]
Take a bit of time, but fixed now: https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/1558
