### ISSUE TITLE
CommandBuffer.SetGlobalMatrixArray only the first index gets populated

### ISSUE THREAD

**Issue by equalsequals** [Unity-Technologies/ScriptableRenderPipeline#1295]
Upon passing a Matrix4x4 array using: 
```
Matrix4x4[] myMatrixArray= new Matrix4x4[2] { Matrix4x4.identity, Matrix4x4.identity };
cmd.SetGlobalMatrixArray("MyMatrixArray", myMatrixArray);
context.ExecuteCommandBuffer(cmd);
```

and sampling it in a Shader, the second index is empty (all 0's).

Breaking it apart into 2 separate float4x4 properties in the Shader and setting them individually works as expected.

Using Unity 2018.1.0f1 and the latest of the Unity 2018.1 branch.

**Comment by RemyUnity** [comment]
Hello @equalsequals ,
I was able to properly set a matrix array through command buffer and properly read all the value from a shader, using same version of Unity and the 2018.1 branch.
Could you maybe share your project or a minimal repro project ?

**Comment by equalsequals** [comment]
Hi @RemyUnity

Apologies for the delayed response, I'm working on a minimalistic repro case. 

For loose context, I am implementing a full-screen Blit around the AfterOpaque Pass, just before the PPS would be executed for Opaque Image Effects. I do a 4-corner frustum per-eye and pack it into a Matrix4x4[2] for use with the target eye index. 

Step-debugging was showing that the matrices were properly populated, but Frame Debugger was showing the array to be all 0's for the right eye (1).

As I mentioned, sending 2 matrices individually and performing a ternary assignment based on the target eye index works, which is an *okay* workaround. I haven't attempted packing a Vector4[8] to see if that would work.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/srp-commandbuffer-dot-setglobalmatrixarray-only-the-first-index-gets-populated
