### ISSUE TITLE
VR support not available in the HDRP

### ISSUE THREAD

**Issue by hectorC** [Unity-Technologies/ScriptableRenderPipeline#1296]
Hello,

Now that Unity 2018.1 has been released, I tried to get the HDRP to work with VR but the HMD doesn't display anything and on the Game window I can see the camera is tracking but the image is not stereo and appears stretched. I know that a few months back support for VR in the HDRP was not implemented and there was mention of it coming in the future. Am I doing something wrong or is VR support not yet implemented? If not, will it come relatively soon? I just need to know in order to plan project development.

Thanks!

**Comment by sebastienlagarde** [comment]
Hi, 
There is no VR support for now for HDRP. The work have started but we don't have ETA for it.
