### ISSUE TITLE
Dynamic Batching disabled temporarily in the current context to avoid z-fighting

### ISSUE THREAD

**Issue by Leandro6758** [Unity-Technologies/ScriptableRenderPipeline#1303]
Before using the Lightweight Pipeline my scene had around 39 draw calls. With the pipeline it jumps to around 70. If I remove it, the calls come down automatically.

An example from the frame-debugger:

With the pipeline (several calls for the floors):

![image](https://user-images.githubusercontent.com/2287313/39612441-fa1dabc8-4f35-11e8-8b6c-2847ab353ba7.png)

No Pipeline (one single call):

![image](https://user-images.githubusercontent.com/2287313/39612460-223b6302-4f36-11e8-8bc6-be58852f7f7f.png)

The floors are all sprites with scale = 1, no rotation, same (opaque material), etc.

The reason as to why it can't batch: Dynamic Batching disabled temporarily in the current context to avoid z-fighting

**Comment by sebastienlagarde** [comment]
@phi-lira any though?

Note that we don't recommend to use dynamic batching, it often result in poor performance.

**Comment by Leandro6758** [comment]
@sebastienlagarde thanks for the response.

Quick question though, not to contradict you or anything, simply to be able to explain the team what's going on.

We were under the impression that reducing Draw Calls was a desired outcome. Our game is GPU bound, so it would potentially help with fill-rate issues. Now, reading that Dynamic Batching can often result in poor performance comes as some kind of paradigm change to us.

Does it mean it's not recommended for the LWRP, because of how it works internally? Or is not recommended in general? And if so, can you shed any light as to the reason why? (or if you can point me to any documentation I can read it myself).

Thanks!!

**Comment by phi-lira** [comment]
Hi Leandro, 

Thanks for reporting this. I've just fixed it for LWRP. We will generate a new package later this week on staging. After some QA that should be on production shortly after.
 
About the dynamic batching. It does have a cost on cpu side as we have to generate and upload the vertex buffers every frame. It won't help you if you are fill rate bound but in some cases it will help if you are driver bound. 

The best alternative to dynamic batching is GPU instancing as you don't pay the cost for setting up those buffers every frame.

**Comment by phi-lira** [comment]
Related to #1207

**Comment by Leandro6758** [comment]
Thanks! We'll do some research about how to properly use GPU instancing then

**Comment by phi-lira** [comment]
Fixed in #1367 Support for Dynamic Batching can be requested in the pipeline asset.
We will generate a new package with this fix tomorrow.
