### ISSUE TITLE
VideoPlayer doesn't work using Lightweight Pipeline

### ISSUE THREAD

**Issue by Leandro6758** [Unity-Technologies/ScriptableRenderPipeline#1310]
I have a VideoPlayer with a small video (for a splash), that works perfectly on iOS and Android. If I use the Lightweight Pipeline, the video doesn't render. Once I remove it, the Video works perfectly again.

With pipeline:

![image](https://user-images.githubusercontent.com/2287313/39636122-af3880f0-4f95-11e8-86dc-4f03261a4f03.png)

No pipeline:

![image](https://user-images.githubusercontent.com/2287313/39636139-c16e9b60-4f95-11e8-8067-d19432805b55.png)

**Comment by sebastienlagarde** [comment]
@phi-lira any though? For HD we have added a dedicated render path for video player, don't know if LW is requiring one too

**Comment by phi-lira** [comment]
Thanks for reporting that. I'll take a look at it.

**Comment by luispedrofonseca** [comment]
Is this still happening? Haven't tested it yet but I'm researching if I should use the LWRP for a new project.

**Comment by neurochems** [comment]
hey all,
i've been running into Leandro6758's original issue. the video imports ok and plays in the preview window. however, upon setting up a VideoPlayer with a Render Texture, and applying the Render Texture to a Material with a LWRP PB shader the video will not play on a mesh, despite the first frame of the video appearing. the video will additionally not play in the Material preview window.
thanks!!

**Comment by WeaselKing** [comment]
Same problem, here. In my situation I have a short video that plays and then a script automatically executes after it finishes. The video is black and there's no sound, but the script fires of at the time it would have finished. It seems to be playing but not sending the video or audio.

**Comment by Verasl** [comment]
Hi All,

Small update here, both the 'Render Texture' and 'Material Override' render modes work fine at the moment, API only should work but I personally haven't tested it, the other two 'Camera Far Plane' & 'Camera Near Plane' require changes to the Video component itself to support SRP(this isn't just an issue in LWRP).

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-videoplayer-doesnt-work-using-lightweight-pipeline
