### ISSUE TITLE
Cloud build failing to build due to LWRP

### ISSUE THREAD

**Issue by Leandro6758** [Unity-Technologies/ScriptableRenderPipeline#1318]
Getting a few of these errors in UCB:

![image](https://user-images.githubusercontent.com/2287313/39674346-bf4640ae-5120-11e8-8d87-805d03e31be7.png)

Example for text search: 
Shader error in 'LightweightPipeline/Standard (Physically Based)': failed to open source file: 'LWRP/ShaderLibrary/InputSurfacePBR.hlsl' at line 148 (on glcore)

Already tried switching to different beta versions and the errors change a bit, but haven't been able to do a successful build since integrating SRP.

Platform is iOS.

**Comment by sebastienlagarde** [comment]
This is a common issue that is solve in 2018.2 and we try to backport to 2018.1.

Workaround to try for this: Re-import SRP folder, reboot Editor then re-import.
Or try erase shader cache (file and directory) in library folder, reboot editor and re-import.

**Comment by ylluminarious** [comment]
I can confirm that erasing the shader cache in the Library folder and rebooting the Editor seems to make the error go away.
