### ISSUE TITLE
 Unsafe code requires the `unsafe' command line option to be specified

### ISSUE THREAD

**Issue by TheRealCatherine** [Unity-Technologies/ScriptableRenderPipeline#1319]
After selecting any of the three (or all 3) render pipelines in Package Manager my project begins showing the following compile errors:

(example for Core):
AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.render-pipelines.core@1.1.5-preview/CoreRP/Shadow/ShadowUtilities.cs(267,51): error CS0227: Unsafe code requires the `unsafe' command line option to be specified. Enable "Allow 'unsafe' code" in the inspector for 'Packages/com.unity.render-pipelines.core/' to fix this error.

(example for HDRP):
AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.render-pipelines.high-definition@1.1.5-preview/HDRP/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs(120,13): error CS0227: Unsafe code requires the `unsafe' command line option to be specified. Enable "Allow 'unsafe' code" in the inspector for 'Packages/com.unity.render-pipelines.high-definition/' to fix this error.

And similar errors for the low resolution pipeline as well.

There are also plenty errors like the following, though I think they may be related to the above:

/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.render-pipelines.lightweight@1.1.5-preview/LWRP/LightweightPipeline.cs(1472,121): error CS0246: The type or namespace name `ClearFlag' could not be found. Are you missing an assembly reference?

I can't figure out any way to follow its suggestion of allowing unsafe code. I've tried checking the allow unsafe box in the Player settings but this had no effect.

To reproduce:

start with this commit: TheRealCatherine/StageMechanic@ca99cd7 using 2018.1.0f2

install Shader Graph via package manager

install any of the 3 pipelines via package manager

**Comment by EIZENHORN91** [comment]
You can manually add “allowUnsafeCode: true” (correct if I forgot how to spell correctly, long ago it was) in manifest.json, but it was be fixed earlier in first betas

**Comment by TheRealCatherine** [comment]
I can try that though I'm unsure of where to add it, is it like:
{
       "allowUnsafeCode: true",
	"dependencies": {
               blahblah
	}
}

or

{
	"dependencies": {
               blahblah {
                 "allowUnsafeCode: true"
              }
	}
}

or some other way?

I'm currently having this issue with 2018.1.0f2 and whatever version of SRP is currently in the Unity Package Manager

**Comment by sebastienlagarde** [comment]
This should be fixed now

**Comment by Nufflee** [comment]
Doesn't seem to be. @sebastienlagarde I'm on the latest version from the PackageManger.

**Comment by Nufflee** [comment]
So I've fixed this issue by manually adding [this](https://github.com/Unity-Technologies/ScriptableRenderPipeline/blob/master/com.unity.render-pipelines.core/CoreRP/com.unity.render-pipelines.core.Runtime.asmdef#L9) line to the that .asmdef file as it doesn't seem that the right version is shipped with the latest release.
