### ISSUE TITLE
Gear VR with  Lightweight Pipeline not work

### ISSUE THREAD

**Issue by play123** [Unity-Technologies/ScriptableRenderPipeline#1328]
Hi I'm using Unity 2018.1.0f2 + LightWeight render pipeline + gear VR  .
App not working and showing black screen. but if I switch to unity normal render pipeline then its work.

**Comment by sebastienlagarde** [comment]
@phi-lira any though?

**Comment by phi-lira** [comment]
Hi, we are looking into this issue atm. Related to #1304

**Comment by phi-lira** [comment]
Fixed in the following PR #1350 This will be backported to 2018.1 soon. We are looking into generating a new package by the end of this week.
