### ISSUE TITLE
VolumeTextureAtlas AddTexture non-matching format error log reports requiredTextureSize instead of requiredTextureFormat

### ISSUE THREAD

**Issue by SteveElbows** [Unity-Technologies/ScriptableRenderPipeline#1338]
As per title, last part of line 68 of VolumeTextureAtlas.cs should be requiredTextureFormat.

Otherwise the error message says expected format of 32 instead of expected format of Alpha8.

**Comment by sebastienlagarde** [comment]
@Wadarass ^^.

Thanks for the report.

**Comment by Wadarass** [comment]
@sebastienlagarde I’ll fix when I bring over my mipmapping changes.

**Comment by sebastienlagarde** [comment]
@Wadarass Can I close this one?

**Comment by Wadarass** [comment]
The fix is still in https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/1343 so let's leave it open till that is merged in.

**Comment by Wadarass** [comment]
Fixed in https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/1439
