### ISSUE TITLE
Inspecting culling result

### ISSUE THREAD

**Issue by giordi91** [Unity-Technologies/ScriptableRenderPipeline#1345]
Good afternoon, I am in the process for a while to try to implement shadows in a custom SRP using the SRP demo from the unity's blog post as a base, right now I butchered the shadow pass from LWRP, code runs fine, I can see the shadow pass being registered in render doc, but no shadows get rendered, 
I don't mean they don't show up in the shadow map, there is not the draw call at all, this led me to think that maybe something is going wrong with the shadow culling result.
When I run the same setup using build-in LWRP, I can see the drawIndexed call in render doc in Shadow.draw.
 
I have tried to get any kind of information out of the culling result but with no luck. Is it possible to expose any kind of information out of it? Ideally would be nice to get all the names of the object that passed or did not pass the culling, if that is too troublesome even just an int saying how many survived the culling would be a help already.

Also, other then the LWRP is there a minimal example of shadows or other more advanced SRP features or any doc on how to deal with it?

Best regards

M.

**Comment by sebastienlagarde** [comment]
@uygar3d any comment?

>Ideally would be nice to get all the names of the object that passed or did not pass the culling, if that is >too troublesome even just an int saying how many survived the culling would be a help already.
There is currently ongoing effort to make something else for the cull result structure and shadow, we will be able to access the number of visible object for shadow after that, however it will stay an opaque structure.

For other example usage of shadow and SRP you can look at the shadow framework in CoreRP (and its usage in HDRP), but no documentation yet about how to use it.

**Comment by uygar3d** [comment]
Culling is a black box right now and done automatically for all lights flagged as shadow casting, based on the light type. Internally this creates a renderqueue and associates it with the light index. You can call GetShadowCasterBounds on the cull results with the right index - this will return false if no object survived culling for that shadow caster. When rendering shadows the DrawShadowsSettings structure must be correctly initialized as this is used to associate the internal renderqueue with the drawcall. Also make sure the splitdata, which is part of DrawShadowSettings is correctly initialized. Check ExtractSpotLightMatrix in ShadowUtilities.cs for how to reset the planes. This will render the entire renderqueue, which is not what you want for point/directional lights, but will be good enough to sanity check what you're doing.

HDRP has its own shadow system, mainly in CoreRP/Shadow and CoreRP/ShaderLibrary/Shadow. A more minimal example of using the core shadow system can be derived from FptlLighting.cs.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/srp-inspecting-culling-result
