### ISSUE TITLE
LWRP Visible Light Popping

### ISSUE THREAD

**Issue by equalsequals** [Unity-Technologies/ScriptableRenderPipeline#1346]
I have a thread about this on the forums: https://forum.unity.com/threads/lwrp-visible-light-popping-issue-with-sorting.530382/

To reiterate my most, even if I am currently under the Visible Light limits (8) I get sporadic popping of Lights when they are set to anything but 'Important'. This is from the 2018.1-experimental branch and 2018.1.0f2

**Comment by sebastienlagarde** [comment]
@phi-lira any though?
Note: 2018.1-experimental, is not officially supported and the problem you have may be fix in 2018.2 upcoming version.

**Comment by equalsequals** [comment]
@sebastienlagarde I've spoken a bit with @phi-lira  about this already. I believe this is fully reproducible in the current release tags for Package Manager as well. I had been observing this through the 2018.1 branch before I made the switch to 2018.1-experimental.

Please let me know if there's any additional info you'd need that would be of assistance.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-lwrp-visible-light-popping
