### ISSUE TITLE
Hololens Deploy Exceptions

### ISSUE THREAD

**Issue by frededk** [Unity-Technologies/ScriptableRenderPipeline#1349]
I have no trouble deploying on my Hololens except when I use the Lightweight Render Pipeline. When I deploy to a Hololens with the LRP the app crashes with a few exceptions:

`'MixedRealityToolkit-Unity.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Devices.Sensors.dll'. Cannot find or open the PDB file.
onecoreuap\drivers\mobilepc\sensors\convergence\services\broker\client\simpledeviceorientationrpcclient.cpp(252)\Windows.Devices.Sensors.dll!642EC578: (caller: 642EB8C3) Exception(1) tid(494) 8007139F The group or resource is not in the correct state to perform the requested operation.
Exception thrown at 0x77A32552 in MixedRealityToolkit-Unity.exe: Microsoft C++ exception: wil::ResultException at memory location 0x014FE4F0.
'MixedRealityToolkit-Unity.exe' (Win32): Loaded 'C:\Windows\System32\ClipboardServer.dll'. Cannot find or open the PDB file.
'MixedRealityToolkit-Unity.exe' (Win32): Loaded 'C:\Windows\System32\rmclient.dll'. Cannot find or open the PDB file.
Exception thrown at 0x5FD5FDA6 (UnityPlayer.dll) in MixedRealityToolkit-Unity.exe: 0xC0000005: Access violation reading location 0x0000005C.
'MixedRealityToolkit-Unity.exe' (Win32): Loaded 'C:\Windows\System32\Faultrep.dll'. Cannot find or open the PDB file.
'MixedRealityToolkit-Unity.exe' (Win32): Loaded 'C:\Windows\System32\dbghelp.dll'. Cannot find or open the PDB file.
'MixedRealityToolkit-Unity.exe' (Win32): Loaded 'C:\Windows\System32\dbgcore.dll'. Cannot find or open the PDB file.
Unhandled exception at 0x5FD5FDA6 (UnityPlayer.dll) in MixedRealityToolkit-Unity.exe: 0xC0000005: Access violation reading location 0x0000005C.`

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-hololens-deploy-exceptions
