### ISSUE TITLE
[LWRP] Multiple Cameras causes Post-Processing disappearing

### ISSUE THREAD

**Issue by beinteractive** [Unity-Technologies/ScriptableRenderPipeline#1356]
Setup a scene like a following:

  - 1st Camera
    - Depth: -1
    - Post-Process Layer
  - 2nd Camera
    - Depth: 0
    - Clear: Depth Only

It expects that a post-processed image has been rendered on the screen, but actually not if the 2nd camera is enabled.

2nd Camera: Enabled
<img width="600" alt="2018-05-14 15 55 22" src="https://user-images.githubusercontent.com/1482297/39982437-51228f68-578f-11e8-96f1-f31d5a766bd7.png">

2nd Camera: Disabled
<img width="600" alt="2018-05-14 15 55 37" src="https://user-images.githubusercontent.com/1482297/39982441-54c269e0-578f-11e8-99c5-f80f39421e3d.png">

See this minimal reproduction project:
https://github.com/beinteractive/LWRP-PostProcessingDisappearingIssue

Note:
A kind of this camera setup is often used for 3D Camera + uGUI Camera.

Reproduced in:
Unity 2018.1.0f2 + Lightweight Render Pipeline 1.1.5-preview

**Comment by sebastienlagarde** [comment]
@RemyUnity ^^Bug report / Test also in HD

**Comment by Verasl** [comment]
@beinteractive out of interest are your Camera settings the same? both have the same MSAA & HDR settings between the two cameras?

One thing to note is that you can put the post effect later on the secondary camera as it generally likes to be added on the last camera in the stack and with the LWRP(maybe also true for HDRP) the UI is always rendered last regardless, postfx is not applied to the UI anyway and unless you are needing different camera transforms/projections for game vs UI it is recommended to use a single camera to avoid the extra added cost of a secondary camera.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-multiple-cameras-causes-post-processing-disappearing
