### ISSUE TITLE
LWRP Shader compile issues

### ISSUE THREAD

**Issue by mihakrajnc** [Unity-Technologies/ScriptableRenderPipeline#1357]
We're using LWRP and we're getting compile errors:

```
Shader error in 'Hidden/LightweightPipeline/Blit': failed to open source file: 'LWRP/ShaderLibrary/Core.hlsl' at line 21 (on glcore)
Compiling Vertex program
Platform defines: UNITY_NO_DXT5nm UNITY_ENABLE_REFLECTION_BUFFERS UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 SHADER_API_DESKTOP UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING

Shader error in 'Hidden/LightweightPipeline/CopyDepth': failed to open source file: 'LWRP/ShaderLibrary/Core.hlsl' at line 18 (on glcore)
Compiling Vertex program
Platform defines: UNITY_NO_DXT5nm UNITY_ENABLE_REFLECTION_BUFFERS UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 SHADER_API_DESKTOP UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING
```

This causes mostly everything to appear pink (apart from the UI). The issue can sometimes be resolved by restarting the editor / deleting the Library folder, however, the main issue is that this also happens on Cloud Build, where it seems to start working at random. Sometimes a new build with no changes will fix the issue, sometimes a clean build will not fix it...

**Comment by unity3d-kr** [comment]
I change relative path to absolute path. and I success console build.

LightweightStandard.shader
~~#include "LWRP/ShaderLibrary/InputSurfacePBR.hlsl"~~
~~#include "LWRP/ShaderLibrary/LightweightPassLit.hlsl"~~
#include "/Assets/ScriptableRenderPipeline/ScriptableRenderPipeline/LightweightPipeline/LWRP/ShaderLibrary/InputSurfacePBR.hlsl"
#include "/Assets/ScriptableRenderPipeline/ScriptableRenderPipeline/LightweightPipeline/LWRP/ShaderLibrary/LightweightPassLit.hlsl"
 
You can change other shader, hlsl files in this way.

**Comment by sebastienlagarde** [comment]
know issue already reported. I will close this one as duplicate.
