### ISSUE TITLE
Some questions about Lightweight Pipeline

### ISSUE THREAD

**Issue by blueloveTH** [Unity-Technologies/ScriptableRenderPipeline#1361]
1) The **MSAA** settings in Camera component has **no effect**,it only depends on LW settings asset.
2) The **Render Mode** in Light component has **no effect**,I set one as important but it still render **per-vertex**,it always **ignores my choice** and sorts the light importance **automatically**,which is not expected.
3) Function **OnRenderImage()** will not be called in LW Pipeline,it is build-in only.I do not want to use Postprocessing Stack because it is too large and low performance.

2018.1.0f2

**Comment by blueloveTH** [comment]
Additional:
This code was used for transparent object works bad
Pass{
    ZWrite On
    ColorMask 0
}
Pass{
    Zwrite Off
    //...
}

But the vertexs of these objects still produce false occlusion.

**Comment by phi-lira** [comment]
Hi, thanks for reporting it. I'll take a look at 1 and 2. About 3 @Chman any comments?

**Comment by Chman** [comment]
Afaik there's no support for `OnRenderImage` on SRPs so you'll either have to use the post-processing stack or write your own effects for LWRP.
