### ISSUE TITLE
Order Independent Transparency

### ISSUE THREAD

**Issue by diegoperini** [Unity-Technologies/ScriptableRenderPipeline#1362]
I'm trying to achieve order independent transparency in LWRP/HDRP. I wonder if there is a way.

**Comment by phi-lira** [comment]
Hey Diego, You forgot to add a description to the issue. Please update it so we can help.

**Comment by diegoperini** [comment]
This issue was created due to an error of mine in one of my git scripts. Sorry for the inconvenience.

I'm trying to achieve order independent transparency in LWRP/HDRP. I wonder if there is a way.

**Comment by phi-lira** [comment]
If you want Order Independent Transparency you can implement depth peeling. http://www.eng.utah.edu/~cs5610/lectures/OrderIndependentTransparency.pdf
