### ISSUE TITLE
Emissive Per Layer?

### ISSUE THREAD

**Issue by sabillano** [Unity-Technologies/ScriptableRenderPipeline#1363]
We used to use Substance Material Layering at my company. Now that it has been deprecated,l looks like this is the way to go. But there is no Emissive per Layer. We had the same issues with Substance long time ago and we had to change the shader on our own. Why everybody forgets about the emissive??

Right now there is one emissive at the end of the LayeredLit Material.
We need to have Emissive as an individual parameter. So we can modify each Layer's Emissive individually. I tried modifying the Emissive parameter from the individual Lit material and Re-Synchronizing but is not transferred to the Layered one, so I guess is not taken on account. Also we would need to be able to modify the Emissive parameter in RT, so this was just a test, Re-Synchronizing in RT is not an option I suppose. 

Since we need this really urgently I would like to ask:
--Is it going to be a featured in the near future? 
--Is it even possible/easy to do it, or is not possible due limitations?

**Comment by conorhynesire** [comment]
This is needed for me also!

**Comment by sebastienlagarde** [comment]
Hi, 

>We used to use Substance Material Layering at my company. Now that it has been deprecated
We have remove the "substance" material in Unity, but nothing prevent you to use Substance layering material and bake the results in textures.

>Right now there is one emissive at the end of the LayeredLit Material.
The layeredLit shader is very big and we chose deliberately to not blend all the textures or mode supported by the Lit shader. This cause Keyword explosion and maintenance issue. We will rely on shader graph to handle all the desired artists cases (once it is ready for HD).

>I tried modifying the Emissive parameter from the individual Lit material and Re-Synchronizing but is not transferred to the Layered one

Emissive is located in BuiltinData, so you will need to report the blending algorthim and sampling macro there. To work with layer, you need to declare properties in layeredLit.hlsl, be sure they are in sync with lit shader (look at baseColor for an example), declare the properties in litProperties.hlsl, sample the textures with macro in IndividualOneLayer.hlsl (which only affect surface data currently, not builtin data, so you will need to re-arrange the code for it, or output an emissive for it. Then you need to blend the result in LayeredData based on the weight. It require also to add 4 Keywords + handling the various combination of emissive mode (if you chose to handle them, like affect albedo emissive per layer).

**Comment by isurfraz** [comment]
@sabillano but shadergraph will solve this so it seems a mute point?

**Comment by sebastienlagarde** [comment]
It is a legitimate request, just as explain above we will not add more feature to the already very complex Layered shader.

**Comment by sabillano** [comment]
Yep, I have been looking at Shader Graph and looks the way to go on this one, the only problem is going to be waiting for the implementation on the HDRP. 
Thank a lot for the responses.
