### ISSUE TITLE
Camera callbacks not working

### ISSUE THREAD

**Issue by TreesAreOP** [Unity-Technologies/ScriptableRenderPipeline#1364]
The OnPreRender and OnPostRender camera methods are not called when using the LWP.  Neither in the Unity Editor nor in a standalone build.
Note: For some reason they get called when the Shader Graph Editor is active.

Unity Version: 2018.1.0f2
SRP Version:  1.1.8-preview
Shader Graph Version: 1.1.8-preview

**Comment by diegoperini** [comment]
They are deprecated as far as I know. You can use `RenderPipeline` events `RenderPipeline.beginCameraRendering` and/or `RenderPipeline.beginCameraRendering` instead.

https://docs.unity3d.com/ScriptReference/Experimental.Rendering.RenderPipeline.html

**Comment by TreesAreOP** [comment]
OK thank you!
