### ISSUE TITLE
TextMeshPro Doesn't Work

### ISSUE THREAD

**Issue by VadimTikhonyuk** [Unity-Technologies/ScriptableRenderPipeline#1366]
Hi, everyone

I used LWR on Android Platform
And TextMeshPro does not work.

![image](https://user-images.githubusercontent.com/13260375/40282930-d4d9d2d2-5c7e-11e8-8190-ddbf14a82646.png)

And Console is clear

I used Unity 2018.1.0f2 and RPL 1.1.5-preview

**Comment by VadimTikhonyuk** [comment]
Using TextMesh from Package Manager fixed this problem!

**Comment by phi-lira** [comment]
Ok. Good to know. I'd just poked them and 1.2.2 should be working. I'll close the issue then.
