### ISSUE TITLE
GBuffers doesn't seem to be cleared correctly

### ISSUE THREAD

**Issue by hayashi1987** [Unity-Technologies/ScriptableRenderPipeline#1368]
In HDRP, GBuffers except RT0(diffuse color) doesn't seem to be cleared every frame.
When I resizing view window size, I can see RT1 is overlapping with past frames (using Frame Debugger).
I added a custom process which uses GBuffer infomation after GBuffer pass, so it must be cleared correctly.

So I inserted a line to HDRenderPipeline.cs such as below, then RT1 was cleared correctly.

>                // Clear GBuffers
>                if (!hdCamera.frameSettings.enableForwardRenderingOnly)
>                {
>                    using (new ProfilingSample(cmd, "Clear GBuffer", CustomSamplerId.ClearGBuffer.GetSampler()))
>                    {
>                        HDUtils.SetRenderTarget(cmd, hdCamera, m_GbufferManager.GetBuffersRTI(), m_CameraDepthStencilBuffer, ClearFlag.Color, CoreUtils.clearColorAllBlack);
>                        
>                        //INSERT
>                        HDUtils.SetRenderTarget(cmd, hdCamera, m_GbufferManager.GetBuffer(1), m_CameraDepthStencilBuffer, ClearFlag.Color, CoreUtils.clearColorAllBlack);
>                    }
>                }
>                // END TEMP

Is this behavior a bug or intended behavior?

Unity Version: 2018.2.0b4
SRP Version: master(f343be310bb2932f784985a92da29a58674df061)

![gbuffer_rt1](https://user-images.githubusercontent.com/20236679/40300485-4db04d44-5d24-11e8-9aef-7e37ab002e7e.png)

**Comment by sebastienlagarde** [comment]
Hi, in HD the GBuffer is not clear for performance reasons (This save 4 fullscreen clear of  32bit target),  the scene is constantly fully rewritten, so no need for a clear. 

However when you do a custom pass on the Gbuffer data after the GBuffer pass you must use the Stencil test to not process no-lighting pixel (StencilLightingUsage.NoLighting: i.e sky for example, or forward material will tag the stencil buffer to not be processed during GBuffer pass) as they don't setup any information in the GBuffer. Clearing it like you do will just put a "default" value, but it will not be used anyway.

See StencilBitMask.LightingMask and StencilLightingUsage.NoLighting

**Comment by hayashi1987** [comment]
Thank you very much!
I tried this solution, and I will probably got good result.

**Comment by sebastienlagarde** [comment]
Hi, Sorry I give you an incomplete answer.  So the bug you mention was due to incorrect clear, and is fix here:
https://github.com/Unity-Technologies/ScriptableRenderPipeline/commit/60f7ccb0f3b2bb7e31c37f70e6d35476dc7da36d

However my statement still remain (the PR is not in master yet) but we will clear GBuffer only in debug mode and not in game mode. Mean you eed to test the stencil to avoid garbadge.
