### ISSUE TITLE
We can't use Unity3d's Terrain Engine In HDSRP?

### ISSUE THREAD

**Issue by frideal** [Unity-Technologies/ScriptableRenderPipeline#1370]
When I open a HDSRP template project,click create 3D terrain.
Nothing happened! There is no 3D terrain in the scene just a GameObject with Terrain Component.

We can't use Unity's Terrain Engine in HDSRP?or how do we create some terrain stuff in HDSRP?

**Comment by sebastienlagarde** [comment]
Hi, Terrain is not supported in HDRP currently.

**Comment by frideal** [comment]
Thanks.
How do we create some "terrain" stuff in HDSRP?
one way is using Height Map with Plance and use PolyBrush to modify the vertex ?

**Comment by sebastienlagarde** [comment]
I haven't really any advice here (Sorry, I am not a terrain developer). 
"Terrain" may be imported from outside for now (i.e created static mesh outside of Unity, and slice it).  This is the method used in this demo: https://blogs.unity3d.com/2018/03/12/photogrammetry-in-unity-making-real-world-objects-into-digital-assets/

**Comment by frideal** [comment]
Thanks.
