### ISSUE TITLE
Type `UnityEngine.Light' does not contain a definition for `lightmapBakeType'

### ISSUE THREAD

**Issue by SunsetOrange** [Unity-Technologies/ScriptableRenderPipeline#1381]
Earlier today I updated Unity to the latest version (Unity 2018.1.1f1). Since then I'm unable to build my project anymore, as I get an error. I have tried uninstalling and reinstalling the SRP Core & HDRP with no change (SRP Core 1.1.8-preview, High Definition Render Pipeline 1.1.8).

The error is as follows:

C:/Users/Michael/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.render-pipelines.high-definition@1.1.8-preview/HDRP/Lighting/GlobalIlluminationUtils.cs(28,50): error CS1061: Type `UnityEngine.Light' does not contain a definition for `lightmapBakeType' and no extension method `lightmapBakeType' of type `UnityEngine.Light' could be found. Are you missing an assembly reference?

**Comment by equalsequals** [comment]
Yeah, I hit this issue too. It appears that using `Light.bakingOutput.lightmapBakeType` ([Docs](https://docs.unity3d.com/ScriptReference/LightBakingOutput.html)) is the run-time equivalent, but it's certainly not obvious.

**Comment by SunsetOrange** [comment]
I copied over the GlobalIlluminationUtils.cs with the new version, and the build process is now successful.
The issue seems resolved. Thanks.
