### ISSUE TITLE
Creating custom shaders for use in HDRP

### ISSUE THREAD

**Issue by StefDevs** [Unity-Technologies/ScriptableRenderPipeline#1395]
Hey is there any guidance available for creating new shaders for use with the HDRP?

For example I'd like to create a version of the decal shader with support for emission and for masking to specific geometry or layers.

Is this well supported?

Thanks,
- Stef

**Comment by sebastienlagarde** [comment]
Hi, 

To write a custom unlit shader this is not too difficult, I provide help here: https://forum.unity.com/threads/convert-to-srp-hd.514377/#post-3387016

We have no way to do surface surface shaders (like buitin unity). Current preferred usage is shader graph but this is only for 2018.2.
Alternative is to copy/paste all Lit directory and update the UI/Lit.Shader/LitData files, but it will be a nightmare to do.

Writing a new lighting model is complex and not documented yet.

Updating decal shader require to:

for opaque:
- update the shader (decal.shader)
- Update the binding and number of render target of the DBuffer (DBufferManager.cs) - i.e add your emission buffer.
- Update the blending of the decal (look at AddDecalContribution in DecalUtilities.hlsl)

Warning: Any extra GBuffer will have impact on performance. Thus why we have limited the number of blendable attribute.

For transparent: Deal with the extra data in the decal atlas (decal are render as cluster decal).



As decal is in heavy development we don't provide documentation.

**Comment by StefDevs** [comment]
Great! Thanks so much for this info - I'm sure it will enough to get me on my way. I'll probably just leave the decals alone for now until it becomes more stable but the info is still appreciated. I can convert my old solution in the mean time if needed.
