### ISSUE TITLE
[LWRP] A problem with using multiple camera and setting Viewport Rect.

### ISSUE THREAD

**Issue by fum1h1ro** [Unity-Technologies/ScriptableRenderPipeline#1454]
When using multiple camera and setting *Viewport Rect*, this problem will occur.

Setup a scene like a following:

* 1st Camera
  * Depth: 0
  * ViewportRect: 0, 0, 0.5, 1(x,y,w,h)
* 2nd Camera
  * Depth: 1
  * ViewportRect: 0.5, 0, 0.5, 1
* 1st Canvas
  * RenderMode: Screen Space - Camera
  * Camera
    * Depth: 2
    * ClearFlags: DepthOnly
    * ViewportRect: 0, 0, 0.5, 1
* 2nd Canvas and Canvas Camera
  * RenderMode: Screen Space - Camera
  * Camera
    * Depth: 3
    * ClearFlags: DepthOnly
    * ViewportRect: 0.5, 0, 0.5, 1

I think, it expects that 1st camera and canvas has rendered left side of screen and 2nd staff has renderied right side of screen.

If not using LWRP gets correct result.

![correct](https://user-images.githubusercontent.com/1317764/40840389-6d3596cc-65e1-11e8-927c-0790ea91a41e.PNG)

But using LWRP gets wrong result.

![wrong](https://user-images.githubusercontent.com/1317764/40840400-7f105314-65e1-11e8-945f-484bdcabf95e.PNG)

See this minimal reproduction project:
https://github.com/fum1h1ro/LWRP-MultipleCameraCanvasIssue

Reproduction in:
Unity2018.1.2f1 + LightweightRenderPipeline1.1.8-preview

Thanks,

**Comment by fum1h1ro** [comment]
It still occurs in 1.1.11-preview.

**Comment by phi-lira** [comment]
Hey @fum1h1ro we fixed some issues in 2.x.x. That requires Unity 2018.2. Is it possible for you to test on it. 
I'm at hackweek this week. I'll take a look at this next week.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-a-problem-with-using-multiple-camera-and-setting-viewport-rect
