### ISSUE TITLE
Shader graph compilation errors

### ISSUE THREAD

**Issue by mihakrajnc** [Unity-Technologies/ScriptableRenderPipeline#1456]
When using ShaderGraph I often get shader compilation errors, after adding a node (has happened with Multiply, OneMinus, etc....):

```
[Warning] Preview shader for graph has 8 errors:
Shader compilation error in graph at line 5 (on ):
Parse error: syntax error, unexpected ',', expecting ')'
Shader compilation error in graph at line 72 (on d3d11):
'TransformObjectToWorld': implicit truncation of vector type
Shader compilation error in graph at line 83 (on d3d11):
'TransformObjectToWorld': implicit truncation of vector type
Shader compilation error in graph at line 84 (on d3d11):
'TransformObjectToWorld': implicit truncation of vector type
Shader compilation error in graph at line 85 (on d3d11):
'TransformObjectToWorld': implicit truncation of vector type
Shader compilation error in graph at line 86 (on d3d11):
'TransformObjectToWorld': implicit truncation of vector type
Shader compilation error in graph at line 92 (on d3d11):
'TransformObjectToWorld': implicit truncation of vector type
Shader compilation error in graph at line 93 (on d3d11):
'TransformObjectToWorld': implicit truncation of vector type
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

In addition to some assertion failed errors:
```
[Assert] Assertion failed: Assertion failed on expression: 'success'
UnityEditor.ShaderUtil:CreateShaderAsset(String)
ShaderGraphImporter.OnImportAsset()    C:/Users/mihak/AppData/Local/Unity/cache/packages/staging-packages.unity.com/com.unity.shadergraph@1.1.9-preview/Editor/Importers/ShaderGraphImporter.cs:75

GUIUtility.ProcessEvent()
```
```
[Assert] Assertion failed: Assertion failed on expression: 'success'
UnityEditor.ShaderGraph.Drawing.MaterialGraphEditWindow:Initialize(String)
ShaderGraphImporterEditor.ShowGraphEditWindow()    C:/Users/mihak/AppData/Local/Unity/cache/packages/staging-packages.unity.com/com.unity.shadergraph@1.1.9-preview/Editor/Importers/ShaderGraphImporterEditor.cs:42

ShaderGraphImporterEditor.OnInspectorGUI()    C:/Users/mihak/AppData/Local/Unity/cache/packages/staging-packages.unity.com/com.unity.shadergraph@1.1.9-preview/Editor/Importers/ShaderGraphImporterEditor.cs:17

GUIUtility.ProcessEvent()
```

When one of these happens, the graph will no longer recover and is unusable. Some of our older graphs also suffer from this issue, however when compiling (for iOS) they apparently compile fine. But we're not able to edit them since everything is pink.

Trying to do "Compile and show code" shows an empty shader block.

Any ideas?

**Comment by sebastienlagarde** [comment]
@pbbastian Thought?

**Comment by pbbastian** [comment]
Which version of Shader Graph is this using?

**Comment by mihakrajnc** [comment]
@pbbastian I'm using ShaderGraph from the LWRP 1.1.6 package, but I also tested it out with the 1.1.10 LWRP package, and got the same results. My Unity version is 2018.1.0f2.

On a side note, when this happens, the shader displays this error: "Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)".

**Comment by OzoneABN** [comment]
Same happed to me just now. Using Unity 2018.1.3f1 and the 1.1.10 LWRP. Using Unity on a Mac for an iOS project.

Are there any clues here yet?

**Comment by OzoneABN** [comment]
A Solution that works for me:
Do not use the Scripting Runtime Version .Net 4.0 in the Player Settings. If I use .Net 3.5 everything works fine.

**Comment by Kink3d** [comment]
Yes, we currently dont support the 4.0 runtime. 

We are moving all our issues to our internal tracking system and are tracking this already so I'll close this.

Thanks
