### ISSUE TITLE
Package Manager dont work with Lite or HD SR!

### ISSUE THREAD

**Issue by deodatopr** [Unity-Technologies/ScriptableRenderPipeline#1460]
![captura](https://user-images.githubusercontent.com/16979750/40861781-f194aa70-65af-11e8-9441-f78fdeb17a3c.PNG)

I did use it on 2018.1.0 & 2018.1.1f1

**Comment by sebastienlagarde** [comment]
@stramit thought ?

**Comment by deodatopr** [comment]
from yestarday is working again, thanks !
