### ISSUE TITLE
Shader Graph blackboard drag state locked

### ISSUE THREAD

**Issue by MatheusFaria** [Unity-Technologies/ScriptableRenderPipeline#1465]
When interacting with the drop-down of a property in the blackboard, it gets stuck in the drag mode, any mouse movement around or in the blackboard drags it along. [I've recorded it](https://youtu.be/BEqczn6On-c), before 17 seconds the drag function it is perfectly working. After I interacted with the "Fresnel Color" Mode drop-down, it gets stuck in the drag action. 

BTW, the blackboard wasn't appearing, I had to delete the `Library` folder and restart Unity to gain access to it.

**Unity Version:** 2018.1.2f1 (on the Lightweight RP example project)

**Comment by Kink3d** [comment]
Hi

We are moving all our issues to our internal tracking system and are tracking this already so I'll close this.

Thanks
