### ISSUE TITLE
Only first pass gets rendered when using multi-pass shaders

### ISSUE THREAD

**Issue by julhe** [Unity-Technologies/ScriptableRenderPipeline#1469]
I'm currently porting over shaders from a project which uses a multipass shader. However, only the first pass gets rendered. If I comment out the first one, only the second one shows up. No Shadergraph, just pure shader code. LWRP.

**Comment by equalsequals** [comment]
LWRP is a Single Pass Renderer, so it doesn't have the concept of a 'ForwardAdd' Pass.

**Comment by julhe** [comment]
I know, but its not about any lightning stuff here.

It's a special effect shader where the inside of the mesh gets a different pass than the outside. Without multipass, its a huge pain to duplicate each material, ansign it to every object and make sure those two materials share the same proppertys, expect for that few who determint wether its the inside or outside pass.

I can understand that multipass feels kinda legacy, but its still usefull for certain effects and I just don't want to miss it.

**Comment by equalsequals** [comment]
That you can do already, if you modify the Render loop. You can add support for additional Passes by modifying the `DrawRendererSettings` for that part of the Render loop. By way of `SetShaderPassName`, you specify an index, in which if a Shader has both Passes present it will do them in order of index.

**Comment by tigershan1130** [comment]
If that's the case, if I wrote a CG shader with baseforward pass only, what about the meta pass that's been computed for GI?

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-only-first-pass-gets-rendered-when-using-multi-pass-shaders
