### ISSUE TITLE
Animation viewer has black background that hides floor grid

### ISSUE THREAD

**Issue by roberto-renzetti-unity** [Unity-Technologies/ScriptableRenderPipeline#1489]
Filing this bug in Git to link with bug on Fogbugz. This issue was found by a Spotlight customer.

https://fogbugz.unity3d.com/f/cases/1044281/

1. What happened 

When viewing a character animation from our project, which uses HDRP, in the Animation viewer, background turns black and makes floor grid invisible when the associated model is dragged into the viewer. 

2. How we can reproduce it using the example you attached

Select any character animations in the Spotlight customer project.  Drag associated model into Animation viewer, background turns black and makes floor grid invisible.  In animation viewer, select the Unity model and background reverts back to grey and grid is visible.  Please see referred fogbugz case for screen captures and project info.

**Comment by FlorinUnity** [comment]
As it is already in fogbugz, I close the issue.
