### ISSUE TITLE
Gizmos don't show up in the game view with HDRP

### ISSUE THREAD

**Issue by roberto-renzetti-unity** [Unity-Technologies/ScriptableRenderPipeline#1491]
Filing this bug in Git to link with bug on Fogbugz. This issue was found by a Spotlight customer.

https://fogbugz.unity3d.com/f/cases/1046467/

1. What happened

When you click on the "Gizmos" button in the Game view window on a HDRP project, Unity does not display any Gizmos

2. How we can reproduce it using the example you attached

Create a HDRP project (you can use the template)
Make sure that the sample scene is displayed and has items that have gizmos.
Switch to the game view
Click the "Gizmos" button on the top right of the game view window.
BUG: no gizmo is shown.

Please look at attached screenshot. On the left we have the scene view where you can see the gizmos (pointed by red arrows), and on the right we have the game view with the gizmos button on, but no gizmo is shown.
![no_gizmos](https://user-images.githubusercontent.com/38924810/41066087-8f94aa0c-6995-11e8-93da-68daf90b42f0.JPG)

**Comment by sebastienlagarde** [comment]
Hi, we found that this is a general SP problem and will dig into it. Thanks for the report.

**Comment by svetliaka92** [comment]
Hello friends.

If i may add - the same issue is happening with the lightweight render pipeline as well. The "Gizmos" button in Game view is clicked, but the gizmos don't show.

**Comment by sebastienlagarde** [comment]
Yes, as said it is a general issue with SRP technology. thanks for the report

**Comment by FlorinUnity** [comment]
As it is already in Fogbugz, I will close the issue.
