### ISSUE TITLE
[LWRP] Hololens - With shadows enabled, the scene is flipped and follows the camera.

### ISSUE THREAD

**Issue by FraFont23** [Unity-Technologies/ScriptableRenderPipeline#1498]
We're developing for Hololens on **Unity 2018.1.0f2**, **LWRP 1.1.10-preview**. 
(We had the same issue making some tries with Unity 2018.2.0b7)

The **Hololens** is connected through the Holographic remote emulation built in Unity using WiFi.

When enabling **Shadows** from the LightweightAsset, the scene is **flipped vertically** and all the objects seem to follow the camera movement. However, the actual Transform position of the GameObjects is not changing. 

With Shadows disabled, the scene works just fine. 

Also, the scene works properly if checked through the editor without the Hololens connected.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-hololens-with-shadows-enabled-the-scene-is-flipped-and-follows-the-camera
