### ISSUE TITLE
Does not find shader include path when BUILDing player if packages are copied to Assets

### ISSUE THREAD

**Issue by ohmaya** [Unity-Technologies/ScriptableRenderPipeline#1502]
##### What happened?
1. Download LWRP from Package Manager, then copy from cache to a 2018.2.0b3 3D project's Assets folder.
2. Use a LightweightAsset.
3. Resolve shader include path issue for the editor by changing LightweightShaderIncludePaths.cs:
paths[index] = Path.GetFullPath("Packages/com.unity.render-pipelines.lightweight");
to:
paths[index] = Path.GetFullPath("Assets/Packages/com.unity.render-pipelines.core@1.1.10-preview");
4. **Build a player, still have shader include path issue**.

##### Which package (Shader graph, LW, HDRP, Core...)?
com.unity.render-pipelines.lightweight@1.1.10-preview

##### Unity template or github source code?
Packages downloaded from Package Manager, then copied from the cache to a 3D project, i.e., manifest.json does not contain dependency to LWRP, this is for internal development/source code modifications.

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
com.unity.render-pipelines.lightweight@1.1.10-preview

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Editor: Windows, Player: Windows, Android

**Comment by ohmaya** [comment]
Will generate \Library\ShaderIncludePaths.txt, which contains \Assets\Packages\com.unity.render-pipelines.core@1.1.10-preview, but not LWRP.

**Comment by ohmaya** [comment]
Seems something to do with HDR, when building, the editor switches to the default scene, whose camera has HDR checked.

**Comment by stramit** [comment]
Please read the main page about how to get the project to 'work with it'. We do not support cloning into assets but instead 'localised packages'.

```This repository consists of a folder that should be cloned outside the Assets\ folder of your Unity project. We recommend creating a new project to test SRP. Do not clone this repo into an existing project unless you want to break it, or unless you are updating to a newer version of the SRP repo.

After cloning you will need to edit your project's packages.json file (in either UnityPackageManager/ or Packages/) to point to the SRP submodules you wish to use. See: https://github.com/Unity-Technologies/ScriptableRenderPipeline/blob/build/automation/TestProjects/GraphicsTests/Packages/manifest.json

This will link your project to the specific version of SRP you have cloned.```

**Comment by ohmaya** [comment]
Do not even need to edit packages.json, it just works as Embeded packages.

**Comment by ohmaya** [comment]
Actually, an older version of README.md said, needs to be placed in the Assets\ folder.

**Comment by ohmaya** [comment]
@stramit 
Although it is said that cloning to /Assets is not supported, quite possible it can work. I guess the main reason that cloning to /Assets is not suggested is: if .json points to /Assets, it gets compiled twice.

**Comment by stramit** [comment]
The shader path export code does not function within the assets folder, which is the cause of the original issue.
