### ISSUE TITLE
Properties break shadergraph on german system

### ISSUE THREAD

**Issue by IARI** [Unity-Technologies/ScriptableRenderPipeline#1519]
##### What happened?
Adding any property to a shadergraph breaks the compiled shader, previews turn purple.
Consider the following simple unlit shader graph asset:
![image](https://user-images.githubusercontent.com/1053417/41262604-17aa27aa-6de2-11e8-9a16-a48a25120b1d.png)
After converting the color node to a property:
![image](https://user-images.githubusercontent.com/1053417/41262642-4a584d08-6de2-11e8-840f-1d233df67370.png)

![image](https://user-images.githubusercontent.com/1053417/41262660-61f57968-6de2-11e8-8d6b-61c0c6c2eb6a.png)

**Important Note** This is running on a german system. Judging from the error, I suspect, that the shader graph code uses string conversions like
```c#
float.Parse(someString)
```
that ignore the locales, which will leads to incorrect results in locations where a comma-character is used instead of a period-charactoer as floating point.
Instead
```c#
float.Parse(someString, CultureInfo.InvariantCulture.NumberFormat)
```
should probably be used.

##### Which package (Shader graph, LW, HDRP, Core...)?
Lightweight Renderer 1.1.10-preview
SRP Core 1.1.10-preview

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
1.1.10-preview ..??

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2018.1 (running on Windows 10)
target platform: webgl

**Comment by martint-unity** [comment]
Hi @IARI 
You are right, we did have an issue with different Locales. But that has been fixed in the latest update so please update and let us know if it still happens. If it does then please open a case in the Unity issue tracker.
Thanks for your thorough feedback of the issue
