### ISSUE TITLE
[LW 1.1.10 -> 2.0.1] Extreme Performance Regression (36 times slower)

### ISSUE THREAD

**Issue by D1no** [Unity-Technologies/ScriptableRenderPipeline#1523]
##### What happened?
I do a lot of research and testing for AR. When updating a test project to Lightweight Render Pipeline 2.0.1 & Shader Graph 2.0.1, the performance drops **rapidly by 36 times**. Experienced on iOS. See the following:

#### Lightweight Render Pipeline: 1.1.10 (LEFT) vs. 2.0.1 (RIGHT)
_As you see, the tracking (simple Vuforia setup) drifts a lot on the right, because the main thread can not keep up for some reason._
![old_lsrp_1 1 10_small](https://user-images.githubusercontent.com/2397125/41284419-844635aa-6e39-11e8-9669-a3eda9f45c38.gif) ![new_lsrp_2 0 1_small](https://user-images.githubusercontent.com/2397125/41284503-c5d5be64-6e39-11e8-83aa-9f9f41165bf9.gif)

Here a comparison of Profile session of the two iOS Builds

##### Before (1.1.10)
![image](https://user-images.githubusercontent.com/2397125/41285382-39f73c58-6e3c-11e8-8f4e-56eed7add191.png)

<details>
  <summary>Full Screenshot</summary>
<a target="_blank" href="https://user-images.githubusercontent.com/2397125/41285083-7e31d2a8-6e3b-11e8-9d2a-fc01df76bdbe.png"><img src="https://user-images.githubusercontent.com/2397125/41285083-7e31d2a8-6e3b-11e8-9d2a-fc01df76bdbe.png" alt="old_lsrp_1 9" style="max-width:100%;"></a>
</details>

##### After (2.0.1)

![image](https://user-images.githubusercontent.com/2397125/41285332-1aa25d06-6e3c-11e8-8221-62fb6115832f.png)

<details>
  <summary>Full Screenshot</summary>
<a target="_blank" href="https://user-images.githubusercontent.com/2397125/41285124-96311670-6e3b-11e8-8ff4-a1f78c53b5d0.png"><img src="https://user-images.githubusercontent.com/2397125/41285124-96311670-6e3b-11e8-8ff4-a1f78c53b5d0.png" alt="new_lsrp_2 1" style="max-width:100%;"></a>
</details>

You'll notice that the Lightweight Pipeline render jumped form 11ms to almost 400ms. Nothing was changed in the project.

##### Which package (Shader graph, LW, HDRP, Core...)?
 - LW 1.1.10 vs 2.0.1 (<- **only difference**)
- Shader Graph 1.1.9 vs 2.0.11 (<- **only difference**)
- LW Profile: High
- Notable: Using GAMMA Color Space because Vuforia does not support LINEAR Color Space

##### Unity template or github source code?
Can be confidentially shared with a Unity GitHub Org Member.
 - Cylinder Tracking 
 - Added Example Scene (static light map)

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
 - 2018.2.0b7 (latest beta at the point of writing)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
 - Windows 10 (latest stable) & MacOS High Sierra (latest stable 10.13.4)
 - Build to iOS min SDK 10.3
 - xCode Version 9.4 (9F1027a)
 - Test Device: iPhone 6S (but same performance drop visible on my iPhone X)

**Comment by D1no** [comment]
@Unity et al. any way to mitigate this? I uploaded this stuff to a google drive folder for internal sharing (vpn etc. blocks your internal bug reporter). Would be great to not have this issue get out of sight

**Comment by Verasl** [comment]
@D1no Hi, I can have a look at this for you, this seems very odd indeed and would be useful to see whats causing this, let me know how I can get my hands on this project and any info I need to get it up and running, I'll test it on an iPhone 6 as it should be capable of running fine there.

**Comment by D1no** [comment]
@Verasl I just send you an email to your github email with the subject "Reproduction - LW 1.1.10 to 2.0.1 Performance Regression"

I am glad you guys made it through Unite Berlin and you're taking a look at this.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-lw-1-dot-1-10-2-dot-0-1-extreme-performance-regression-36-times-slower
