### ISSUE TITLE
Metal: Fragment shader missing buffer binding at index 3 (_LightIndexBuffer / PBR Master)

### ISSUE THREAD

**Issue by rvilgalys** [Unity-Technologies/ScriptableRenderPipeline#1524]
##### What happened?

Hello,

I upgraded to the latest 2.0.1 preview for the Lightweight Pipeline & Shadergraph packages. I'm now getting the following warning when I edit a shader: 

'Metal: Fragment shader missing buffer binding at index 3 (_LightIndexBuffer / PBR Master)'

This will repeat 4 times, and then there is no preview of the shader results in the Shadergraph editor. Downgrading everything back to the last version works fine again. 

##### Which package (Shader graph, LW, HDRP, Core...)?

Shader Graph

##### Unity template or github source code?

Template from Package Manager

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?

Packages are Shadergraph 2.0.1 Preview, LW Render Pipeline 2.0.1, Render Pipeline Core 2.0.7

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity Version 2018.2.0b7
MacOS is target and OS

**Comment by 6b796c65** [comment]
I'm also seeing this error after updating and objects using the LRP standard shader are not rendering. 
I'm running beta 7 on MacOS and seeing the error with both MacOS and iOS build targets.

**Comment by rvilgalys** [comment]
Just tried an update to 2.0.3 and this still appears to be an issue.

**Comment by phi-lira** [comment]
Hey, sorry for the delay. We've got Unite and hackweek hapenning last and this week that's why things are a little bit slow now. I'll take a look at this issue next week.

**Comment by rvilgalys** [comment]
Thanks and no worries! Let me know if I can help at all. Been very impressed with everything.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-metal-fragment-shader-missing-buffer-binding-at-index-3-lightindexbuffer-slash-pbr-master
