### ISSUE TITLE
HDRP Strange compile popup box with 2.0.3-preview 

### ISSUE THREAD

**Issue by hippocoder** [Unity-Technologies/ScriptableRenderPipeline#1531]
##### What happened?
When compiling own scripts, a process appears to be launched that causes HDRP shaders to compile (at least I think it's the shaders).

##### Which package (Shader graph, LW, HDRP, Core...)?
HDRP 2.0.3-preview

##### Unity template or github source code?
Package manager

##### Which package version or branch 
2108.2 beta 7

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Editor, Windows 10

**Comment by sebastienlagarde** [comment]
Hey, thanks for this report.

We are aware of the problem, the sahder seems to unecessary recompile when it shouldn't. A fix should comme in a later version of Unity. Thanks

**Comment by sebastienlagarde** [comment]
So we have two cases, one fix is coming but there is also another problem that may appear and for this you just need to delete your library folder (if you have upgrade from an older project to a new version)

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/srp-hdrp-strange-compile-popup-box-with-2-dot-0-3-preview
