### ISSUE TITLE
UV Set for LW shader

### ISSUE THREAD

**Issue by LeGiangAnh** [Unity-Technologies/ScriptableRenderPipeline#1534]
##### What happened?
I cannot find the UV Set setting for LW Shaders. Is it possible to have Animated Scrolling texture in LW?
##### Which package (Shader graph, LW, HDRP, Core...)?
LW
##### Unity template or github source code?
Unity template
##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
2.0.3-preview
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Android, iOS

**Comment by phi-lira** [comment]
Yes, it's possible. You need to define constants such as _MainTex_ST in your shader. This is required for the batcher to cache this Constant Buffer across many frames and reduce drawcall cost.

You can copy what you need from InputSurfacePBR.hlsl or InputSurfaceSimple.hsls.
Let me know if this works for you.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-uv-set-for-lw-shader
