### ISSUE TITLE
[LWRP] WaterTile.cs  Camera.current null exception.

### ISSUE THREAD

**Issue by AlexandreVinet** [Unity-Technologies/ScriptableRenderPipeline#1541]
##### What happened?
In WaterTile.cs ( From Standard Assets/Environment ) when rendering the Game view, the function OnWillRenderObject() is called with a Camera.current = null.

##### Which package (Shader graph, LW, HDRP, Core...)?
LW

##### Unity template or github source code?
Standard Assets code.

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
Preview from 2018.1.1f1

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Windows Editor. Play Mode.

**Comment by sebastienlagarde** [comment]
OnWillRenderObject() can't be use to render reflection (cause infinite recursion in SRP), use BeginCameraRendering instead

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-watertile-dot-cs-camera-dot-current-null-exception
