### ISSUE TITLE
Shader Graph: Converting Color to Property causes compilation errors

### ISSUE THREAD

**Issue by Trojaner25** [Unity-Technologies/ScriptableRenderPipeline#1549]
##### What happened?
The following errors occur when converting a Color node (does not matter if HDR or not) to a property in the graph editor:

>Compilation error in graph at line 7 (on ):
Parse error: syntax error, unexpected ',', expecting ')'
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

![image](https://user-images.githubusercontent.com/1809172/41492050-381e8686-7105-11e8-891e-953049297b53.png)

Reverting by deleting the property fixes the errors again.
Note that I did not notice this issue on converting other types (e.g. Vector1, Vector2...) to properties.

##### Which package (Shader graph, LW, HDRP, Core...)?
Shader graph

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
Shader Graph: 2.0.3-preview
Render Pipeline Core Library: 2.0.3-preview
Lightweight Render Pipeline: 2.0.3-preview

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2018.2.0b7 Standalone Windows with .NET 4.0 compatible Mono backend.

**Comment by Kink3d** [comment]
Hi

We currently dont support the 4.0 runtime.

We are moving all our issues to our internal tracking system and are tracking this already so I'll close this.

Thanks
