### ISSUE TITLE
Accessing vertex dimensions

### ISSUE THREAD

**Issue by m3rt32** [Unity-Technologies/ScriptableRenderPipeline#1552]
I am trying to manipulate vertexes in shader graph, I can get vertex positions with position node but I cannot seperate them like, i.vertex.x or something ? Is that possible ?

**Comment by JustTheCoolDude** [comment]
Use a split node to seperate vectors https://github.com/Unity-Technologies/ShaderGraph/wiki/Split-Node.
r, g and b on the split node would respectively be the x, y and z of a vector3.

**Comment by m3rt32** [comment]
Thanks pal, you made my day.
