### ISSUE TITLE
Shader only applies bright pink tint

### ISSUE THREAD

**Issue by SusterDrifter** [Unity-Technologies/ScriptableRenderPipeline#1559]
##### What happened?
When the shader is applied to any object, it becomes just as the preview shows, a bright pink tint. Have tried remaking new shader but the problem still persist.

![image](https://user-images.githubusercontent.com/39788874/41575690-42473f6e-73b6-11e8-98da-53de78957f0e.png)

##### Which package (Shader graph, LW, HDRP, Core...)?
Lightweight

##### Unity template or github source code?
https://github.com/SusterDrifter/SlimRhinos-Hart-DollHouse.git

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
Lightweight Render Pipeline 1.1.10-preview

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2018.1.5f2, Standalone windows

**Comment by GithubPrankster** [comment]
Having the same problem.

**Comment by sebastienlagarde** [comment]
Hey, I think it was a feature not implemented in 1.1.10-preview. Poking @pbbastian for more information.

**Comment by pbbastian** [comment]
Hi, can I get you to create a case on the Unity Issue Tracker instead? Sorry that it's a bit inconvenient, but it works much better with our internal QA workflows :)
