### ISSUE TITLE
Shader Graph: Right click to drag canvas

### ISSUE THREAD

**Issue by jjxtra** [Unity-Technologies/ScriptableRenderPipeline#1563]
##### What happened?
Navigating shader graph canvas is awkward

##### Which package (Shader graph, LW, HDRP, Core...)?
Shader graph

##### Unity template or github source code?
2.0.3 package manager

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
Unity 2018.2 beta, Windows 10 x64

Please allow right click to drag the canvas around just like the scene view. It is really hard to navigate shader graph at the moment.

**Comment by jjxtra** [comment]
Alt right click works, it would be nice to not have to press alt since right click drag without alt does nothing at the moment

**Comment by Kink3d** [comment]
Hi,

Use middle click to drag canvas. Thanks.

**Comment by jjxtra** [comment]
That is slightly less annoying than alt+left, but right click would be even easier, just like the scene view :) Hope you will consider it as right click drag does nothing currently.
