### ISSUE TITLE
Decimal values as parameters corrupts the current shader graph file.

### ISSUE THREAD

**Issue by STUDIOCRAFTapps** [Unity-Technologies/ScriptableRenderPipeline#1564]
##### What happened?
I created a vector1 and set its value to 0.2 and the shader stopped working (It became magenta).
The texture preview were no longer displaying the proper texture but instead, error textures (The black and magenta grid texture)

##### Which package (Shader graph, LW, HDRP, Core...)?
PBR Graph shader

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
Lastest version, Shader Graph 1.1.9-preview, Lightweight Pipeline/SRP Core 1.1.10-preview, 

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Windows 10, 2018.1.0b13

**Comment by STUDIOCRAFTapps** [comment]
Also I keep getting this error: Assertion failed: Assertion failed on expression: 'success'

**Comment by Kink3d** [comment]
Hi

We are moving all our issues to our internal tracking system and are tracking this already so I'll close this.

Thanks
