### ISSUE TITLE
[ShaderGraph] Sub graph not working

### ISSUE THREAD

**Issue by mathias234** [Unity-Technologies/ScriptableRenderPipeline#1567]
##### What happened?
I was trying to make a subgraph for mixing uvs (to reduce tiling) and when I go to try it out I get a lot of errors (and just a pink shader):
https://prnt.sc/jwv89e

##### Which package (Shader graph, LW, HDRP, Core...)?
Shader Graph

##### Unity template or github source code?
Shader Subgraph: https://pastebin.com/PYSQi9kD
Shader Test: https://pastebin.com/1qHdHkiF

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
2.0.3-preview

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2018.2.0b9, Windows, Standalone Windows

**Comment by Kink3d** [comment]
Hi,

This is fixed by PR: #1458. This will land in an upcoming beta.
