### ISSUE TITLE
[HDRP] Volumetric Fog not working as expected in Unity 2018.2b9

### ISSUE THREAD

**Issue by James9270** [Unity-Technologies/ScriptableRenderPipeline#1572]
##### What happened?
After updating to Unity 2018.2.0b9, and opening a project where I had enabled volumetric fog, I noticed that the volumetric fog was not appearing, and there was an error in the console: 
"Compute shader (VolumeVoxelization): Property (_VolumeMaskAtlas) at kernel index (1) has mismatching texture dimension (expected 3, got 2)"

To check if this problem was occurring because of something in my main project, I created a new project, installed the HDRP package (2.0.3-preview), enabled volumetric fog. The same issue occurred:
![image](https://user-images.githubusercontent.com/13963586/41635081-a788e0d6-73fb-11e8-9951-5567392e9315.png)

Opening the same project, with Unity 2018.2.0b8, causes things to back to normal:
![image](https://user-images.githubusercontent.com/13963586/41635312-f7f2c75c-73fc-11e8-9816-8203918e6848.png)

##### Which package (Shader graph, LW, HDRP, Core...)?
HDRP.

##### Unity template or github source code?
Package manager.

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
2.0.3-preview.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2018.2.0b9, Windows 10, standalone windows.

**Comment by EvgeniiG** [comment]
Hi James,

Thanks for the bug report!

The issue has been fixed on the master branch: https://github.com/Unity-Technologies/ScriptableRenderPipeline/commit/c844dc9038316f99fbe72e48857c1122f35a0b54

We will also backport it to 2018.2.

Evgenii

**Comment by EvgeniiG** [comment]
I have backported the fix to 2018.2: https://github.com/Unity-Technologies/ScriptableRenderPipeline/commit/6a7d64e5d72f9a90fbe177332f1aea6dd4070464

**Comment by EvgeniiG** [comment]
As a workaround, create at least one Density Volume with a Density Map (mask 3D texture).
