### ISSUE TITLE
[LWRP] Assigning Render Texture gives black Screen (only on build)

### ISSUE THREAD

**Issue by Immudelki** [Unity-Technologies/ScriptableRenderPipeline#1575]
##### What happened?
Getting black screen / UI disappearing **(only on build)** when using render texture set on secondary camera 

Repro steps:
- Create CameraA
- Create CameraB - screen space mode
- Create RenderTexture and assign it to CameraB

> Editor Play Mode works
> Build works

- Add LWRP
> Editor Play Mode works
> **Build gives black screen / Worldspace UI disappears**

From what I see, maybe it's depth issues ?..

##### Which package (Shader graph, LW, HDRP, Core...)?
LWRP

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
1.1.10-preview

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2018.1.5.f1, 2018.2.b9 (probably all as it's more linked to LWRP anyway...)
Standalone Windows64bits

**Comment by Phiphel** [comment]
We have the same issue.

@phi-lira any news on fix?

**Comment by tmthomsen** [comment]
We have the same issue. Works fine in editor, but screen shows up as black in Android build.
Right now it seems our only solution is to not use LWRP :/
Any news on the matter would be greatly appreciated.

**Comment by phi-lira** [comment]
Hi Guys, sorry for the delay. We are at hackweek this week. Next week I'll take a look at the issues opened here and in our issue tracker.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:


https://issuetracker.unity3d.com/issues/lwrp-assigning-render-texture-gives-black-screen-only-on-build
