### ISSUE TITLE
Suggestion: Move ShaderGraph to a separate package in Package manager like it used to be or add it in HDRP

### ISSUE THREAD

**Issue by ArtyIF** [Unity-Technologies/ScriptableRenderPipeline#1584]
##### What happened?
I want to use ShaderGraph with HDRP, but I have to install LWRP to use it. Why? How about you give it a separate package in package manager or at least integrate it in HDRP as well?
##### Which package (Shader graph, LW, HDRP, Core...)?
Shader graph
##### Unity template or github source code?
Package manager. Which option is it?
##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)? (lol a typo plz fix)
2.0.3-preview
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2018.2.0b9, Windows 10 Build 1803, target - standalone Windows

**Comment by sebastienlagarde** [comment]
Hi, I think you are confuse or miss something. The SG package is separated and LW and HD depends on it. You can get SG package alone, or only HD with SG.

**Comment by ArtyIF** [comment]
Well I can't see it in my Package Manager window anywhere.

![a screenshot of package manager](https://user-images.githubusercontent.com/8017858/41718085-8d5a1508-7564-11e8-9721-0d6710abc006.png)

And the wiki says:

> To use the Shader Graph in your project either start a new project using the Lightweight 3D Template or download the Lightweight Render Pileine via the Package Manager. The Shader Graph will be downloaded automatically for your use in either of these cases.

**Comment by ArtyIF** [comment]
Oh wait. I'm dumb. It's in Shader submenu.
