### ISSUE TITLE
[Bug] Parse error on .NET 4.x API Compatibility Level and locales that use comma for floating point numbers instead of a dot

### ISSUE THREAD

**Issue by ArtyIF** [Unity-Technologies/ScriptableRenderPipeline#1588]
##### What happened?
If you use .NET 4.x API Compatibility Level and a locale that uses a comma for floating-point numbers instead of a dot (i.e. Russian) then, when using a float/vector/color with a comma in there, it results in a parsing error.

An example in my shader: `_AsphaltColor("Asphalt Color", Color) = (0,2509804,0,2509804,0,2509804,1)`. This is the code I got when I copied the shader code (RMB -> "Copy Shader" for those who don't know).
##### Which package (Shader graph, LW, HDRP, Core...)?
Shader graph
##### Unity template or github source code?
Package manager
##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
2.0.3-preview
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2018.2.0b9, Windows 10 build 1803, standalone windows

**Comment by ArtyIF** [comment]
There are 3 workarounds I came up with:

1. Don't use floating-points with comma or colors that are not (0 or 255, 0 or 255, 0 or 255, 0 or 255) for now and put them in properties. Duh.
2. Use .NET 3.5. I can't, because I need one of the new .NET APIs (`System.Threading.Tasks` if you care).
3. Switch your system locale to English. There's a Windows edition that allows a single language only (usually OEMs install these). And I have one.
![screenshot and translation](https://user-images.githubusercontent.com/8017858/41734404-7a087cda-758f-11e8-865e-2ccdffd97216.png)

Use them if you can.

**Comment by martint-unity** [comment]
hi @ArtyIF ,
I have located the issue and I have a fix. This will be available next update to shader graph. 
It is in this c89783f05923ebab3bdb5878d4c787d95bb7fd20
