### ISSUE TITLE
Shader graphs with transparent surface type do not render with render queue value of 2000

### ISSUE THREAD

**Issue by adamzl** [Unity-Technologies/ScriptableRenderPipeline#1592]
##### What happened?
Custom shader (shader graph) with a master node's surface type set to transparent, set to a material with a render queue value of 2000 (the Geometry setting) does not render. While experimenting with reproduction I found inconsistent reproduction with an exact value, one piece of geometry is lost at 2500, another is lost at 2999. Generally transparent surface shaders don't render anything when set at 2000.

##### Reproduction
1. Create a "PBR Graph" shader.
2. In the shader editor click the gear icon on the master node, set the "Surface" to "Transparent".
3. Save, create two materials with the shader. Create two cubes and give each one of the materials.
4. Set the render queue value of one of the materials to 2000, alternatively use the drop down and set to "Geometry".
5. Cube should disappear.

##### Which package (Shader graph, LW, HDRP, Core...)?
Shader graph + LW

##### Unity template or github source code?
LW template

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
2018.2.0b4 + Lightweight Render Pipeline 2.0.3-preview package

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2018.2.0b4, Windows 10.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-plus-shadergraph-shader-graphs-with-transparent-surface-type-do-not-render-with-render-queue-value-of-2000
