### ISSUE TITLE
LWRP Post Processing Issue

### ISSUE THREAD

**Issue by m3rt32** [Unity-Technologies/ScriptableRenderPipeline#1595]
I am trying to create image effects with shader graph. But because of OnRenderImage not supported, I have no clue how to make one. What is the way of making post processing effects via shader graph?

**Comment by demonixis** [comment]
You've to use the PostProcessing StackV2. There is an API to [create your custom effects](https://github.com/Unity-Technologies/PostProcessing/wiki/Writing-Custom-Effects)

**Comment by m3rt32** [comment]
Thanks for answer, I've tried that but I am getting "Invalid shader" error. Here is the example project that I've tried:
https://github.com/m3rt32/ShaderGraphCustomPostProcessingTest

**Comment by sebastienlagarde** [comment]
This is currently not supported.

**Comment by m3rt32** [comment]
So, we cant use shader graph for post processing/image effects right now ?

**Comment by sebastienlagarde** [comment]
No.
