### ISSUE TITLE
Lenovo Daydream Flicker

### ISSUE THREAD

**Issue by jeffkingdev** [Unity-Technologies/ScriptableRenderPipeline#1597]
##### What happened?
Lenovo Daydream is flickering at random times in both eyes (but often not the same time in both eyes).  If I just render the default plank scene this happens.

Also, the shadow map does not seem to be in sync with both eyes.  The shadows don't seem to be right as they clash with both eyes.  They look different in each eye, but they are way off on the ground too.

##### Which package (Shader graph, LW, HDRP, Core...)?
LWRP 2.0.4 -- however, I tried all the way down to 1.1.11 and it still happens.

##### Unity template or github source code?
Unity VR template and my own scene.

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
Unity 2018.2.0b9

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2018.2.0b9
Target Android on Lenovo Mirage Solo (Daydream).
Windows 10 machine

Is this happening to anyone else with this device?

**Comment by juancarlosgdm** [comment]
I have the same issue but with Unity 2018.1.0f2. Any interesting discovery since you posted?

**Comment by jeffkingdev** [comment]
I have not :( .  I'm waiting to hear if anyone from Unity can see what's going on.  If you use the standard rendering (not LWRP) then it works fine.

I am having such a hard time with LWRP and VR.  I'm hoping they get it all working properly soon.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/srp-lenovo-daydream-flicker
