### ISSUE TITLE
Non-deterministic camera grouping/order between Windows and MacOS/iOS, very inconvenient render-loop API

### ISSUE THREAD

**Issue by N-01** [Unity-Technologies/ScriptableRenderPipeline#1598]
##### What happened?
I have 3 cameras responsible for Game-view.

1 "Main" - has Render Texture
2 "Additive" - has Render Texture
3 "Blend" - renders a Quad to ViewPort

I'm trying to handle them myself in a fixed order with custom code fo each Camera. 
But i face a lot of issues. 

For some reason there are multiple RenderLoop calls per frame, with Unity passing cameras to it in somewhat arbitrary and UNWANTED order/groups.

It still works on Windows with couple annoying workarounds.

On MacOS, Blend Camera output was Black until i deleted Render Texture that wasn't used by any camera on the scene. Which is already scetchy... On top of that, sometimes it only calls Render Loop for Blend camera or calling it 2 times in a row. Which breaks me rendering altogether.

How can i avoid this kind of ridiculous behaviour? Is there a way to customize Render Loop calls?
There's no way most of Game Dev's who can benefit from custom Render Loop are satisfied with the Pipeline that passes Cameras in arbitrary order and forces you to treat them Generically, instead of having strict order defined by user and knowing exactly what you get every frame.

##### Which package (Shader graph, LW, HDRP, Core...)?

Core

##### Unity template or github source code?

I used LWRP as a starting code.

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?

2018.1

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2018.1.13 Windows, Mac, iOS

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/srp-non-deterministic-camera-grouping-slash-order-between-windows-and-macos-slash-ios-very-inconvenient-render-loop-api
