### ISSUE TITLE
(Minor) SRP DebugUpdater - optional?

### ISSUE THREAD

**Issue by hippocoder** [Unity-Technologies/ScriptableRenderPipeline#1599]
##### Which package (Shader graph, LW, HDRP, Core...)?
UnityEngine.Experimental.Rendering (CORE)

##### Unity template or github source code?
PM

##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?

2018.2+ (certainly not _2108.2_ which is sometime in the future).

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Editor / Standalone

Problem is that this always spawns. I've edited the source to prevent it but I'm really controlling about pretty much everything, and this pops up like a festering boil to taunt me. Please kindly make this fellow optional... :)

**Comment by sebastienlagarde** [comment]
This is already fix in the branch iirc.
