### ISSUE TITLE
If I used SRP my old shaders can't work?

### ISSUE THREAD

**Issue by chaolunner** [Unity-Technologies/ScriptableRenderPipeline#1600]
Only use ShaderGraph and SRP provided shader is really ok for me!
But seem like ShaderGraph create shader, code editing can't be used.
And some of the common functions are not well supported, eg. Outline and Transparent shader with depth writes.
Like Shader Forge or Amplify Shader Editor also don't support mulit-pass (Amplify Shader Editor have a template feature should support mulit-pass but really hard to use for me), But we still can use code editing, I don't know how unity wants to solve these problems.

**Comment by alindmanUnity** [comment]
If you would like to build on a shader that you've made in Shader Graph via HLSL code, go tot he master node of your graph and Right Click -> Copy Shader. Paste that into a clean shader file and you should be able to keep working from there and access the functions that we don't currently support in the graph.
Does that help?

**Comment by miccall** [comment]
@alindmanUnity  very useful ，thanks
