### ISSUE TITLE
LWRP - Shadow cascades double tris of scene

### ISSUE THREAD

**Issue by LeGiangAnh** [Unity-Technologies/ScriptableRenderPipeline#1607]
##### What happened?
When I use two Shadow cascades, the scene draws more than double of tris. Is this expected behavior?
##### Which package (Shader graph, LW, HDRP, Core...)?
LW
##### Unity template or github source code?
Unity package.
##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?
2.0.4-preview
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2018.2b7

**Comment by phi-lira** [comment]
Hey thanks for reporting this. This is a current known issue. Part of it is due to SRP missing the hook up to enable dynamic batching for shadow caster and another part is that LWRP is sometimes generating more casters per cascade than builtin.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-shadow-cascades-double-tris-of-scene-1
