### ISSUE TITLE
[LWRP] Wildly different shadow quality in scene view vs game view

### ISSUE THREAD

**Issue by prodigga** [Unity-Technologies/ScriptableRenderPipeline#1616]
##### What happened?
We have our game camera up fairly high, and we set the Shadow Distance small enough and Near clipping plane close enough on our camera that we can get nice looking shadows with smaller shadow atlas sizes. 

This works really well, but it means our scene view is a complete mess to look at!

Here is an example of a sphere from the game view:
![image](https://user-images.githubusercontent.com/185220/42196965-f3b83664-7ec3-11e8-8eac-943a1debd115.png)

And here is scene view:
![image](https://user-images.githubusercontent.com/185220/42196976-014b3362-7ec4-11e8-8dda-0976f9568215.png)

Here is an example with some fence posts that cast realtime shadows (Everything else is baked)
![image](https://user-images.githubusercontent.com/185220/42197044-47b7dde6-7ec4-11e8-88c6-9d84f877debd.png)

Here is the same section in scene view, you can see how it would be kind of annoying to work with the scene when objects look like this:
![image](https://user-images.githubusercontent.com/185220/42197077-6fd29438-7ec4-11e8-9096-4c98f39010d5.png)

##### Which package (Shader graph, LW, HDRP, Core...)?
LW
##### Unity template or github source code?
Unity Package
##### Which package version or branch (1.1.8-preview, 2.0.0-preview, 2018.1, 2018.1-experiment, 2108.2...)?

2.0.4-preview

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Targeting Android, Windows Operating system, Unity 2018.2.0b10

**Comment by phi-lira** [comment]
This seems related to the camera shadow distance on scene view being high by default. While we don't provide a proper fix, a workaround it to open LightiweightPipeline.cs and set cullinParameters.shadowDistance to your desired distance or increasing the atlas resolution temporarily.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-wildly-different-shadow-quality-in-scene-view-vs-game-view
