### ISSUE TITLE
[LWRP] Light layer culling not working

### ISSUE THREAD

**Issue by Immudelki** [Unity-Technologies/ScriptableRenderPipeline#1647]
Culling mask/layer of directional light doesn't work properly.

Steps:
-Create new project by selecting **Lightweight RP (Preview)** **(uses lightweight 1.1.4-preview)**
-Disable light auto bake, clear generated lighting
-Set Directional Light culling mask to Water Layer Only & Realtime Mode
= Lights which should only affect water layer does affect default layer assets

![issue](https://user-images.githubusercontent.com/21196587/42503449-ff5bd3f2-8438-11e8-9fe7-cc796c448a95.png)

_Note: the light cull works when shadows of the directional lights are disabled or that 'nothing' is used as mask.

(Windows 10 64bits - Unity 2017.1.7f1)

**Comment by Immudelki** [comment]
Hm I think It's the same issue as this one ? https://github.com/Unity-Technologies/ScriptableRenderPipeline/issues/1019

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-light-layer-culling-not-working
