### ISSUE TITLE
HDRP Particles system remake?

### ISSUE THREAD

**Issue by frideal** [Unity-Technologies/ScriptableRenderPipeline#1648]
HDRP will make a new Particles system?
Unity team will Provide new particle shader (particle system)for HDRP?

I port my "Standard Particles" to HDRP most of them become invisible and material become purple.

Thanks.

**Comment by jjejj87** [comment]
I think the HDRP team will make the standard particle shader compatible soon.

I don't think they are working on a new Particle System though.

**Comment by sebastienlagarde** [comment]
Hi shirunken unlit particles are supported.
Shiruken lit particles aren't.
The main solution for hdrp for particles will be the new vfx editor that should come as experimental in 2018.3 or 2019.1
