### ISSUE TITLE
documentation sets a bad example!

### ISSUE THREAD

**Issue by benblo** [Unity-Technologies/ScriptableRenderPipeline#383]
https://docs.unity3d.com/2017.2/Documentation/ScriptReference/Experimental.Rendering.RenderPass.html
Documentation gives a very good advice "NOTE: DO NOT ALLOCATE NEW RENDERPASSATTACHMENTS EVERY FRAME!"... but then later it allocates no less than 6 arrays in the loop, per frame: `new[] { albedo, specRough, normal, emission }`, etc.
I know those are only C# arrays, not tracked Unity Objects, but they will still very much create garbage
So please, cache all those arrays in the constructor (and why not mark them all readonly, as well as the RenderPassAttachment members).

**Comment by sebastienlagarde** [comment]
Sorry for the delay, is this related to SRP? LW/HD? Can't find the code mention (but the issue is very old now so....)

**Comment by benblo** [comment]
Yes it's old but it's still right there in the docs: https://docs.unity3d.com/ScriptReference/Experimental.Rendering.RenderPass.html
<code>
            // Start the first subpass, GBuffer creation: render to albedo, specRough, normal and emission, no need to read any input attachments
            using (new RenderPass.SubPass(rp, **new[]** { m_Albedo, m_SpecRough, m_Normal, m_Emission }, null))
</code>

**Comment by sebastienlagarde** [comment]
@strandborg any correction?

**Comment by strandborg** [comment]
Yes, the example in the docs should be corrected.
