### ISSUE TITLE
Compiling errors in Unity 2017.2b9

### ISSUE THREAD

**Issue by AlexandreFiset** [Unity-Technologies/ScriptableRenderPipeline#386]
Not sure if here is the right place to report this, but importing the ScriptableRenderLoop in an empty project (with PostProcess Stack) in Unity 2017.2 latest beta prints ~400 errors in the console, the first one being:

/ScriptableRenderLoop/ScriptableRenderPipeline/HDRenderPipeline/HDRenderPipeline.cs(217,17): error CS1061: Type `UnityEngine.Rendering.CommandBuffer' does not contain a definition for `SetComputeMatrixParam' and no extension method `SetComputeMatrixParam' of type `UnityEngine.Rendering.CommandBuffer' could be found.
​
Anyway to work around this? Or am I doing something wrong? 
Cheers!

**Comment by JacobSmaga** [comment]
It's probably because they are using 2017.3 already, Try downloading this (It's 2017.3 alpha) it might work https://forum.unity3d.com/threads/presets-feature.491263/

**Comment by AlexandreFiset** [comment]
Well I just found the "releases" tab and now feel like an idiot. The master simply doesn't work at all with any version of Unity, including 2017.3 alpha. Downloading 2017.2 tag now.

**Comment by sebastienlagarde** [comment]
Yes, as this repository is use internally as main development repository the master tend to be out of sync with the latest public version of Unity. We regularly create a "Release" of the code so users are able to compile it with available public version.

**Comment by JacobSmaga** [comment]
Hello Sebastien, Can we expect to get updated 2017.2b9 release this week? Latest one is +1 month old and i see that SRP got many new features such as: Volumetric Lighting, Clear Coat shader etc.

**Comment by aras-p** [comment]
The head of the master branch here will be following "latest unity internal master" for a while, as it has always been. Right now that is _way_ beyond 2017.2 actually; currently it's actually 2017.3 alpha builds, but will soon become 2018.1 codebase. Until we "ship this" in an actual Unity release, the master hence will always be "too new", sorry!

**Comment by AlexandreFiset** [comment]
Thanks Aras for clearing this up. So should we assume this won't ship until 2018.x ? 😅

**Comment by sebastienlagarde** [comment]
We hope to deliver a first "release" for 2018.1

**Comment by haolange** [comment]
Excuse me, I downloaded the 2017.1 version of SRP. Why did it prompt the project file created by 2017.1.Beta3 when it opened?
