### ISSUE TITLE
how to render reflection with SRP?

### ISSUE THREAD

**Issue by benblo** [Unity-Technologies/ScriptableRenderPipeline#517]
We have a custom water solution that uses OnWillRenderObject() to take a snapshot of the scene into an RT.
The thing is, with SRP now OnWillRenderObject() is not called anymore (at least not in editor, though I've seen it called in builds :s), which is great... but then what's the replacement?

What's the best practice for this kind of systems now? To me this is akin to shadows, but custom.
I'm happy firing my own custom event, but what's the proper way of gathering the visible water planes in the first place?
Not that I have thousands of them, so I probably could just iterate and check Renderer.isVisible (is that still maintained with SRP? if so at what stage?), or use the CullingGroup API, though that's a bit cumbersome to setup and only does sphere-check not frustum-check, or... feels like there should be an easy one-stop solution to just filter a list of renderers to be processed C#-side.

I'm (still) on Unity 2017.1.1f1 btw.

**Comment by shawmakesmusic** [comment]
My solution was https://docs.unity3d.com/ScriptReference/Application-onBeforeRender.html

**Comment by sebastienlagarde** [comment]
This post should help: https://forum.unity.com/threads/feedback-wanted-scriptable-render-pipelines.470095/page-8#post-3408481

**Comment by phi-lira** [comment]
As a reference for future. We added the following callbacks:

public static event Action<Camera[]> beginFrameRendering;
public static event Action<Camera> beginCameraRendering;
