### ISSUE TITLE
2017.3.0b10 Warnings with HDPipe

### ISSUE THREAD

**Issue by AlexandreFiset** [Unity-Technologies/ScriptableRenderPipeline#609]
Hi,

Not sure if this is specific to my Surface Book (940M), but I have these warnings while playing in an empty scene with HDPipe:

- CommandBuffer: temporary render texture _AmbientOcclusionTexture not found while executing  (SetComputeTextureParam)
- CommandBuffer: temporary render texture _ShadowMaskTexture not found while executing  (SetComputeTextureParam)
- CommandBuffer: temporary render texture _VelocityTexture not found while executing  (SetComputeTextureParam)

Just wanted to report them just in case it is hardware-specific and maybe something you would like to check out.

Cheers!

**Comment by sebastienlagarde** [comment]
Thanks for the report!
Yes it is know problem and isn't hardware specific. But good to report anyway in case we missed it. Cheers.

**Comment by sebastienlagarde** [comment]
Fixed in latest master and 2018.1 branch
