### ISSUE TITLE
SRP does not work with public 2017.3.0f3 on Mac?

### ISSUE THREAD

**Issue by RamiroOliva** [Unity-Technologies/ScriptableRenderPipeline#750]
I'm sure this is install-related issue but I just downloaded latest SRP sources and kicked it into an empty Unity 2017.3.0f3 project on a Mac and it blowed up with tons of errors, missing namespaces, pink materials, etc.

Any hint ?

**Comment by JacobSmaga** [comment]
Unity 2018.1 Beta which includes SRP comes out in a few days, Just wait.

**Comment by RamiroOliva** [comment]
Alright - thanks.

**Comment by sebastienlagarde** [comment]
You can use the pre-release 2017.3 with 2017.3 binaries
