### ISSUE TITLE
Mobile devices support

### ISSUE THREAD

**Issue by niexuchina** [Unity-Technologies/ScriptableRenderPipeline#768]
Hi. 
Is this available on mobile devices such and Android and IOS phones?
How can I use it on mobile devices?
Thanks. :)

**Comment by sebastienlagarde** [comment]
Hey, 

Lightweight render pipeline is running on all platform
HD is for compute shader capable platform only, currently Metal is barely supported

**Comment by niexuchina** [comment]
Thanks. :)
