### ISSUE TITLE
Projectors + LW renderpipe causing crash

### ISSUE THREAD

**Issue by williamj-unity** [Unity-Technologies/ScriptableRenderPipeline#773]
Repro steps:

To repro with project:
1) Open the projector scene
2) enter playmode or switch to game window
3) Observe crash 

Additional steps:
4) Open the project again 
5) Remove the lightweight render pipe asset from the graphics settings. 
6) Enter playmode
7) Observe, no crash and expected projector results

[EditorProjectorCrash.log](https://github.com/Unity-Technologies/ScriptableRenderPipeline/files/1619664/EditorProjectorCrash.log)
Please ping me for the project. It's too large to upload here.

**Comment by sebastienlagarde** [comment]
I don't know if projector are supported. @phi-lira ?

**Comment by phi-lira** [comment]
Hi. We haven't added support to projectors yet in LW. I'll look into that.

**Comment by phi-lira** [comment]
Hi, I've confirmed recently that projections are not going to be supported by SRP. Therefore, I'll close the issue.
