### ISSUE TITLE
UnityException: FindKernel failed

### ISSUE THREAD

**Issue by Gui205** [Unity-Technologies/ScriptableRenderPipeline#843]
When i open the demo scene i got this error : 

`UnityException: FindKernel failed
UnityEngine.Experimental.Rendering.EncodeBC6H..ctor (UnityEngine.ComputeShader shader) (at Assets/ScriptableRenderPipeline/Core/CoreRP/EncodeBC6H.cs:39)
UnityEngine.Experimental.Rendering.HDPipeline.HDRenderPipeline..ctor (UnityEngine.Experimental.Rendering.HDPipeline.HDRenderPipelineAsset asset) (at Assets/ScriptableRenderPipeline/HDRenderPipeline/HDRP/HDRenderPipeline.cs:314)
UnityEngine.Experimental.Rendering.HDPipeline.HDRenderPipelineAsset.InternalCreatePipeline () (at Assets/ScriptableRenderPipeline/HDRenderPipeline/HDRP/HDRenderPipelineAsset.cs:14)
UnityEngine.Experimental.Rendering.RenderPipelineAsset.CreatePipeline () (at C:/buildslave/unity/build/Runtime/Export/RenderPipeline/RenderPipelineAsset.cs:19)
UnityEngine.Experimental.Rendering.RenderPipelineManager.PrepareRenderPipeline (IRenderPipelineAsset pipe) (at C:/buildslave/unity/build/Runtime/Export/RenderPipeline/RenderPipelineManager.cs:51)
UnityEngine.Experimental.Rendering.RenderPipelineManager.DoRenderLoop_Internal (IRenderPipelineAsset pipe, UnityEngine.Camera[] cameras, IntPtr loopPtr) (at C:/buildslave/unity/build/Runtime/Export/RenderPipeline/RenderPipelineManager.cs:24)
UnityEditor.AssetPreviewUpdater:CreatePreviewForAsset(Object, Object[], String)`

**Comment by sebastienlagarde** [comment]
Two thing to check:
- Do you have a SRPMARKER file in your root ScriptableRenderPipeline folder ? (it is present in our github project)
- If yes, then you have certainly merge code on an already created project. Try close Unity and erase your shaderCache folder and file shaderCache.db.
- If it still doesn't work, erase your project Library folder

**Comment by Gui205** [comment]
Yes i have SRPMARKER in my asset root. 

- I erase my shadercache => No change 
- Erase Library folder =>Work 

Thanks !

**Comment by pointcache** [comment]
I have the same issue, i deleted Library couple of times to no avail.

**Comment by sebastienlagarde** [comment]
All these issues should be fixed now in latest master and 2018.1 branch
