### ISSUE TITLE
Unity 2017.3.0p1 error CS0246

### ISSUE THREAD

**Issue by EddieSoloProjects** [Unity-Technologies/ScriptableRenderPipeline#876]
Assets/ScriptableRenderPipeline/ScriptableRenderPipeline/Core/CoreRP/Editor/IncludePaths/CoreShaderIncludePaths.cs(9,10): error CS0246: The type or namespace name `ShaderIncludePath' could not be found. Are you missing an assembly reference?

I tried deleting the Library folder. Didn't help

**Comment by sebastienlagarde** [comment]
Hi, 
If you use 2017.3 you need to use the corresponding tagged release: https://github.com/Unity-Technologies/ScriptableRenderPipeline/releases

This error mean that you use a more recent Github code than your current binaries version are handling.

**Comment by EddieSoloProjects** [comment]
Thanks that Fixed the issue.
