### ISSUE TITLE
Extensible HD Pipeline?

### ISSUE THREAD

**Issue by KarimLUCCIN** [Unity-Technologies/ScriptableRenderPipeline#898]
https://github.com/Unity-Technologies/ScriptableRenderPipeline/blob/2f6aa8302d3847b44928977a49955f64c58ebf99/ScriptableRenderPipeline/HDRenderPipeline/HDRP/HDRenderPipeline.cs#L662

Could the Render function be authored in a way that makes it easy to be extended? (protected variables as opposed to private, Render function made of different virtual stages as opposed to a monolithic bloc).

I wish I could have a custom logic for the cameras but still use exactly the same pipeline otherwise, or have a way to add a single pass in between GBuffer and the rest without having to reimplement all of the pipeline.

**Comment by sebastienlagarde** [comment]
Not what you are asking, but see: https://forum.unity.com/threads/feedback-wanted-scriptable-render-pipelines.470095/page-8#post-3408481 . We have various discussion internally about extension. Our priority however is first to ship a working product.
