### ISSUE TITLE
Negative scale on gameobjects sometimes borks rendering

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/ScriptableRenderPipeline#902]
[SRP-LW-NegativeScale.zip](https://github.com/Unity-Technologies/ScriptableRenderPipeline/files/1697190/SRP-LW-NegativeScale.zip)

Found using Unity 2018.1.0b6, SRP LW 0.1.28

To reproduce: In the attached project, change any component of the scale of the cube marked "this cube" to negative.

Expected Result: Cube is rendered, albeit "backwards" (which is observably no different from rendering with positive scale for a cube).
Observed Result: All gameobjects no longer render.

**Comment by stramit** [comment]
Hi jack. We think we have fixed this issue. It looks like a core unity rendering bug and required changes to unity.exe (i.e not a LW change). It should be fixed for beta 10 :)

**Comment by jackpr-unity** [comment]
I am currently running through a full test pass on 2018.1.0b10.  I can't repro this - the problem looks fixed to me.
