### ISSUE TITLE
Broken Baked Emission

### ISSUE THREAD

**Issue by StewMcc** [Unity-Technologies/ScriptableRenderPipeline#929]
Lightweight-SRP-0.1.28 Unity-2018.1
Repro steps:
 - Open 005_LitBakedEmission
 - Rebake lighting
 - Notice sphere emissive on self, but no longer emissive on other static objects.

Comments:
Bizarrely temperamental, will move sphere around scene and rebuild lighting, and sometimes it will work but not consistently.

**Comment by Verasl** [comment]
This is fixed now, it was due to the meta pass somehow wanting world space vertex coords rather than object space, hence why it could work if you had your mesh close to or at origin.
