### ISSUE TITLE
Can I get better performance on mobile devices with using SRP than with using Vertex lit render patch and this shader and how?

### ISSUE THREAD

**Issue by AGeorgy** [Unity-Technologies/ScriptableRenderPipeline#975]
﻿Shader "Unlit/VertexColor"
{
	Properties
	{
		_Collor ("Main Collor", Color) = (1,1,1,1)
	}

	CGINCLUDE
	uniform float4 _Collor;

	struct vertOutput
	{
		float4 vertex : SV_POSITION; // clip space position output
		fixed4 color: TEXCOORD0; // texture coordinate output
	};

	vertOutput Vertex (
		float4 vertex : POSITION0, // vertex position input
		half4 color : COLOR0
		)
	{
		vertOutput output;
		output.vertex = UnityObjectToClipPos(vertex);
		output.color = color;
		return output;
	}

	fixed4 Fragment (vertOutput input) : SV_Target
	{
		return fixed4(_Collor.rgb * input.color.rgb, 1);
	}
	ENDCG

	SubShader
	{
		Tags 
		{ 
			"Queue" = "Geometry"
			"RenderType"="Opaque"
			"LightMode" = "Always"
		}

		Pass
		{
			CGPROGRAM
			#pragma vertex Vertex
			#pragma fragment Fragment
			ENDCG
		}
	}
}

**Comment by sebastienlagarde** [comment]
@phi-lira any comment?

**Comment by phi-lira** [comment]
SRP should be marginally faster than vertex render path. We are currently making improvements to reduce the CPU side state management overhead. Therefore the performance gap should increase even more between them. 

You can make your shader work with Lightweight Pipeline if you remove the "LightMode" = "Always" tag from your subshader.

**Comment by AGeorgy** [comment]
Thankyou @phi-lira. Yes I had a test of that shader with SRP and really didn't notice any performance difference. But I had to ask, maybe I was wrong. Ok, anyway thanks.
